import { useState } from 'react'
import { useOperations } from '../../state/useOperations'
import { Active, AdminList, Check, Editor, Field } from '../../components/admin/AdminUI'
import type { CommonCode } from '../../types/systemCatalog'
export default function CodesPage() {
 const w=useOperations(),[group,setGroup]=useState(''),[active,setActive]=useState(''),[draft,setDraft]=useState<CommonCode|null>(null),groups=[...new Set(w.operations.codes.map(c=>c.group))],existing=!!draft&&w.operations.codes.some(c=>c.id===draft.id)
 const rows=w.operations.codes.filter(c=>(!group||c.group===group)&&(!active||String(c.active)===active)).sort((a,b)=>a.group.localeCompare(b.group)||a.order-b.order)
 return <><AdminList title="공통코드" description="선택 사업과 독립된 플랫폼 전역 코드 마스터 · 기존 업무 상태키와 이력은 유지됩니다." rows={rows} rowKey={c=>c.id} searchText={c=>`${c.group} ${c.code} ${c.label}`} onCreate={()=>setDraft({id:crypto.randomUUID(),group:group||groups[0],code:'',label:'',description:'',order:10,active:true})} extraFilter={<><Field label="코드그룹"><select value={group} onChange={e=>setGroup(e.target.value)}><option value="">전체 그룹</option>{groups.map(g=><option key={g}>{g}</option>)}</select></Field><Field label="사용상태"><select value={active} onChange={e=>setActive(e.target.value)}><option value="">전체</option><option value="true">활성</option><option value="false">비활성</option></select></Field></>} columns={[{key:'group',label:'코드그룹',render:c=>c.group},{key:'code',label:'코드',render:c=><button className="text-button" onClick={()=>setDraft({...c})}>{c.code}</button>},{key:'label',label:'표시명',render:c=>c.label},{key:'description',label:'설명',render:c=>c.description},{key:'order',label:'표시순서',render:c=>c.order},{key:'active',label:'사용상태',render:c=><Active value={c.active}/>},{key:'action',label:'업무',render:c=><button className="text-button" onClick={()=>w.save({kind:'code',value:{...c,active:!c.active}})}>{c.active?'비활성화':'활성화'}</button>}]} />{w.feedback}
 {draft&&<Editor title={existing?'공통코드 수정':'공통코드 등록'} onClose={()=>setDraft(null)} onSave={()=>w.save({kind:'code',value:draft})}><Field label="코드그룹"><input required list="common-code-groups" readOnly={existing} value={draft.group} onChange={e=>setDraft({...draft,group:e.target.value})}/><datalist id="common-code-groups">{groups.map(g=><option key={g} value={g}/>)}</datalist></Field><Field label="코드"><input required readOnly={existing} value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value})}/></Field><Field label="표시명"><input required value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/></Field><Field label="설명"><textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></Field><Field label="표시순서"><input required type="number" min="0" value={draft.order} onChange={e=>setDraft({...draft,order:Number(e.target.value)})}/></Field><Check label="사용" checked={draft.active} onChange={value=>setDraft({...draft,active:value})}/></Editor>}
 </>
}
