import { useState } from 'react'
import { useOperations } from '../../state/useOperations'
import { AdminList, Check, Editor, Field } from '../../components/admin/AdminUI'
import { DataTable, DetailDialog, DetailList, StatusBadge } from '../../components/common/ui'
import { jobStatus } from '../../data/operations'
export default function IntegrationsPage({programId}:{programId:string}) {
 const w=useOperations(),[selected,setSelected]=useState(''),[action,setAction]=useState<'재처리'|'재검증'|null>(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[fail,setFail]=useState(false),[status,setStatus]=useState('')
 const rows=w.operations.integrations.filter(i=>i.programId===programId),item=rows.find(i=>i.id===selected),title=w.data.programs.find(p=>p.id===programId)?.name||'외부 연동'
 const start=(mode:'재처리'|'재검증')=>{setAction(mode);setReason('');setConfirmed(false);setFail(false)}
 return <><AdminList title={`${title} 연동 관리`} description="플랫폼 전역 연동 상태·이력 관리 · 실제 API/인증/은행 규격은 TBD이며 모든 처리 결과는 Mock입니다." rows={rows.filter(i=>!status||i.status===status)} rowKey={i=>i.id} searchText={i=>`${i.target} ${i.name} ${i.method}`} extraFilter={<Field label="연동 상태"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">전체</option>{Object.entries(jobStatus).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></Field>} columns={[{key:'name',label:'연동 대상 / 업무',render:i=><button className="text-button" onClick={()=>setSelected(i.id)}>{i.target}<span className="cell-sub">{i.name}</span></button>},{key:'method',label:'방식 / 방향',render:i=>`${i.method} / ${i.direction}`},{key:'status',label:'상태',render:i=><StatusBadge tone={i.status==='healthy'?'success':'warning'}>{jobStatus[i.status]}</StatusBadge>},{key:'success',label:'마지막 성공',render:i=>i.runs.filter(r=>r.result==='success').at(-1)?.at||'없음'},{key:'failure',label:'마지막 실패 / 최근 오류',render:i=><>{i.runs.filter(r=>r.result==='failure').at(-1)?.at||'없음'}<span className="cell-sub">{i.status==='healthy'?'현재 오류 없음':i.runs.filter(r=>r.result==='failure').at(-1)?.message||'중지'}</span></>},{key:'count',label:'최근 송신 / 수신',render:i=>`${i.runs.filter(r=>r.action!=='재검증').at(-1)?.sent||0} / ${i.runs.filter(r=>r.action!=='재검증').at(-1)?.received||0}건`}]} />{w.feedback}
 {item&&!action&&<DetailDialog title="외부 연동 상세" onClose={()=>setSelected('')}><DetailList items={[{label:'연동 대상 / 업무',value:`${item.target} / ${item.name}`},{label:'연동 설명',value:item.description},{label:'현재 방식 / 방향',value:`${item.method} / ${item.direction}`},{label:'상태',value:jobStatus[item.status]},{label:'상세 규격',value:item.specification}]} /><div className="admin-actions"><button className="button secondary" disabled={item.status==='stopped'} onClick={()=>start('재처리')}>Mock 재처리</button><button className="button secondary" disabled={item.status==='stopped'} onClick={()=>start('재검증')}>Mock 재검증</button></div><h3>최근 처리 이력</h3><DataTable caption="외부 연동 처리 이력" rows={[...item.runs].reverse()} rowKey={r=>r.id} columns={[{key:'at',label:'처리일시 / 작업',render:r=>`${r.at} / ${r.action}`},{key:'result',label:'결과 / 송신·수신',render:r=>`${r.result==='success'?'성공':'실패'} / ${r.sent}·${r.received}건`},{key:'message',label:'내용',render:r=>r.message}]} /><h3>오류 이력 · 복구 후에도 보존</h3><DataTable caption="외부 연동 오류 이력" rows={item.runs.filter(r=>r.result==='failure')} rowKey={r=>r.id} columns={[{key:'at',label:'발생시각',render:r=>r.at},{key:'message',label:'오류',render:r=>r.message}]} /></DetailDialog>}
 {item&&action&&<Editor title={`외부 연동 ${action}`} onClose={()=>setAction(null)} onSave={()=>w.save({kind:'externalRun',integrationId:item.id,runId:item.runs.at(-1)!.id,action,reason,confirmed,fail})}><p className="full-width">{item.target} / {item.name} · 실제 전송·정산·지급 데이터는 변경하지 않습니다.</p><Field label="처리 사유"><textarea value={reason} onChange={e=>setReason(e.target.value)} /></Field><Check label="대상과 중복 처리 방지 범위를 확인했습니다" checked={confirmed} onChange={setConfirmed}/><Check label="실패 결과 시연" checked={fail} onChange={setFail}/></Editor>}
 </>
}
