import { useState } from 'react'
import { AdminList, Check, Editor, Field } from '../../components/admin/AdminUI'
import { DataTable, DetailList, StatusBadge } from '../../components/common/ui'
import { jobStatus } from '../../data/operations'
import { useOperations } from '../../state/useOperations'
export default function JobsPage() {
  const { operations, save, feedback } = useOperations(), [selected, setSelected] = useState('job-2'), [status, setStatus] = useState('all')
  const [retryId, setRetryId] = useState(''), [reason, setReason] = useState(''), [confirmed, setConfirmed] = useState(false), [fail, setFail] = useState(false)
  const job = operations.jobs.find(j => j.id === selected), last = job?.runs.at(-1)
  return <><AdminList title="자동 작업 현황" description="Health Check / Monitoring · 실행주기와 Scheduler 정의는 조회 전용입니다. 재실행은 내장 Mock 데이터만 처리합니다." rows={operations.jobs.filter(j => status === 'all' || j.status === status)} rowKey={j => j.id} searchText={j => `${j.name} ${j.area}`} extraFilter={<Field label="현재상태"><select value={status} onChange={e => setStatus(e.target.value)}><option value="all">전체</option>{Object.entries(jobStatus).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></Field>} columns={[
    { key: 'name', label: '작업명 / 업무영역', render: j => <button className="text-button" onClick={() => setSelected(j.id)}>{j.name}<span className="cell-sub">{j.area}</span></button> }, { key: 'frequency', label: '실행주기', render: j => j.frequency }, { key: 'state', label: '현재상태', render: j => <StatusBadge tone={j.status === 'healthy' ? 'success' : 'warning'}>{jobStatus[j.status]}</StatusBadge> }, { key: 'last', label: '마지막 실행 / 정상실행', render: j => <>{j.runs.at(-1)?.at}<span className="cell-sub">정상: {j.runs.findLast(r => r.result === 'success')?.at || '없음'}</span></> }, { key: 'next', label: '다음 예정', render: j => j.nextAt }, { key: 'count', label: '처리건수 / 소요시간', render: j => `${j.runs.at(-1)?.count}건 / ${j.runs.at(-1)?.seconds}초` }, { key: 'error', label: '최근 오류', render: j => j.runs.findLast(r => r.result === 'failure')?.message || '없음' },
  ]} />{feedback}{job && <section className="panel admin-detail"><div className="panel-heading"><h2>{job.name}</h2><button className="button primary" disabled={job.status === 'stopped' || !last} onClick={() => { setRetryId(last!.id); setConfirmed(false); setFail(false); setReason('') }}>안전한 재실행</button></div><DetailList items={[{ label: '현재상태', value: jobStatus[job.status] }, { label: '마지막 결과', value: last?.message }, { label: '오류 상세', value: job.runs.findLast(r => r.result === 'failure')?.message || '없음' }]} /><p className="muted">실제 POS 수집·전송·입금 조회·알림 발송은 수행하지 않습니다. 재실행 성공 후에도 과거 오류 이력은 보존합니다.</p><DataTable caption="상세 실행이력" rows={[...job.runs].reverse()} rowKey={r => r.id} columns={[{ key: 'at', label: '처리일시', render: r => r.at }, { key: 'result', label: '결과', render: r => r.result === 'success' ? '성공' : '실패' }, { key: 'metrics', label: '처리 / 소요시간', render: r => `${r.count}건 / ${r.seconds}초` }, { key: 'error', label: '오류 / 상세', render: r => r.message }, { key: 'id', label: '실행 ID / 재실행 원본', render: r => <>{r.id}<span className="cell-sub">{r.retryOf || '정기 실행'}</span></> }]} /></section>}{retryId && job && <Editor title="안전한 Mock 재실행" onClose={() => setRetryId('')} onSave={() => save({ kind: 'retry', jobId: job.id, runId: retryId, reason, confirmed, fail })}><p className="full-width">대상: {job.name} / 원본 실행 {retryId} · 동일 대상의 중복 제외 Mock 처리</p><Field label="재실행 사유"><textarea value={reason} onChange={e => setReason(e.target.value)} /></Field><Check label="대상 범위와 중복 제외 처리를 확인했습니다" checked={confirmed} onChange={setConfirmed} /><Check label="Mock 실패 시나리오" checked={fail} onChange={setFail} /></Editor>}</>
}
