import { useState } from 'react'
import { Active, AdminList, Check, Editor, Field } from '../../components/admin/AdminUI'
import { notificationTypes } from '../../data/operations'
import { useOperations } from '../../state/useOperations'
import type { NotificationSetting } from '../../types/operations'
export default function NotificationsPage() {
  const { operations, data, save, feedback } = useOperations(), [draft, setDraft] = useState<NotificationSetting | null>(null), [state, setState] = useState('all')
  const rows = operations.notifications.map(n => ({ ...n, type: notificationTypes.find(t => t.id === n.id)! })), type = notificationTypes.find(t => t.id === draft?.id)
  const toggle = (values: string[], id: string, yes: boolean) => yes ? [...new Set([...values, id])] : values.filter(v => v !== id)
  return <><AdminList title="알림 관리" description="개발자가 등록한 유형과 Trigger는 조회 전용입니다. 수신범위·채널·시점·반복·기준값의 운영 설정을 관리합니다." rows={rows.filter(n => state === 'all' || String(n.active) === state)} rowKey={n => n.id} searchText={n => `${n.type.name} ${n.type.area} ${n.type.trigger}`} extraFilter={<Field label="사용상태"><select value={state} onChange={e => setState(e.target.value)}><option value="all">전체</option><option value="true">사용</option><option value="false">중지</option></select></Field>} columns={[
    { key: 'name', label: '알림명 / 업무영역', render: n => <button className="text-button" onClick={() => setDraft(structuredClone(operations.notifications.find(s => s.id === n.id)!))}>{n.type.name}<span className="cell-sub">{n.type.area}</span></button> }, { key: 'trigger', label: 'Trigger', render: n => n.type.trigger }, { key: 'target', label: '수신대상', render: n => <>{n.roleIds.map(id => data.roles.find(r => r.id === id)?.name || id).join(', ')}<span className="cell-sub">{n.organizationIds.length ? n.organizationIds.map(id => data.organizations.find(o => o.id === id)?.name || id).join(', ') : '전체 조직 (선택 Role 범위)'}</span></> }, { key: 'channel', label: '채널 / 시점', render: n => <>{n.channels.join(', ')}<span className="cell-sub">{n.timing} · {n.repeat ? '반복' : '1회'}</span></> }, { key: 'threshold', label: '임계값', render: n => n.threshold === null ? '해당 없음' : `${n.threshold}${n.type.unit}` }, { key: 'active', label: '사용상태', render: n => <Active value={n.active} /> },
  ]} />{feedback}{draft && type && <Editor title={`${type.name} 운영 설정`} onClose={() => setDraft(null)} onSave={() => save({ kind: 'notification', value: draft })}><p className="full-width">등록 유형: {type.id} · Trigger: {type.trigger} (편집 불가)</p><Check label="알림 사용" checked={draft.active} onChange={active => setDraft({ ...draft, active })} /><Field label="발송시점"><input value={draft.timing} onChange={e => setDraft({ ...draft, timing: e.target.value })} /></Field><Check label="반복 발송" checked={draft.repeat} onChange={repeat => setDraft({ ...draft, repeat })} />{type.unit && <Field label={`임계값 (${type.unit})`}><input type="number" min={type.min} max={type.max} value={draft.threshold ?? ''} onChange={e => setDraft({ ...draft, threshold: e.target.value === '' ? null : Number(e.target.value) })} /></Field>}<fieldset className="ops-options"><legend>수신 Role</legend>{data.roles.map(r => <Check key={r.id} label={r.name} checked={draft.roleIds.includes(r.id)} onChange={yes => setDraft({ ...draft, roleIds: toggle(draft.roleIds, r.id, yes) })} />)}</fieldset><fieldset className="ops-options"><legend>수신 조직 (미선택 시 전체 조직)</legend>{data.organizations.map(o => <Check key={o.id} label={o.name} checked={draft.organizationIds.includes(o.id)} onChange={yes => setDraft({ ...draft, organizationIds: toggle(draft.organizationIds, o.id, yes) })} />)}</fieldset><fieldset className="ops-options"><legend>채널 · 실제 발송 없음</legend>{['시스템 알림', 'SMS', '알림톡'].map(c => <Check key={c} label={c} checked={draft.channels.includes(c)} onChange={yes => setDraft({ ...draft, channels: toggle(draft.channels, c, yes) })} />)}</fieldset></Editor>}</>
}
