import { useState } from 'react'
import { AdminList, Editor, Field } from '../../components/admin/AdminUI'
import { DataTable, DetailList, StatusBadge } from '../../components/common/ui'
import { versionStatus } from '../../data/operations'
import { useOperations } from '../../state/useOperations'
import type { ExcelTemplate, TemplateVersion } from '../../types/operations'
const split = (v: string) => v.split(',').map(s => s.trim()).filter(Boolean)
const today = () => new Date().toISOString().slice(0, 10)
export default function TemplatesPage() {
  const { operations, save, download, feedback } = useOperations()
  const [selected, setSelected] = useState(operations.templates[0]?.id), [versionId, setVersionId] = useState(''), [status, setStatus] = useState('all')
  const [draft, setDraft] = useState<ExcelTemplate | null>(null), [version, setVersion] = useState<TemplateVersion | null>(null)
  const [required, setRequired] = useState(''), [optional, setOptional] = useState('')
  const t = operations.templates.find(t => t.id === selected), v = t?.versions.find(v => v.id === versionId) ?? t?.versions.at(-1)
  return <><AdminList title="Excel 양식" description="업무별 공식 Interface의 Version과 적용기간을 관리합니다. 다운로드는 Excel에서 열 수 있는 Mock CSV입니다." rows={operations.templates.filter(t => status === 'all' || t.versions.at(-1)?.status === status)} rowKey={t => t.id} searchText={t => `${t.name} ${t.area} ${t.usage}`} onCreate={() => setDraft({ id: crypto.randomUUID(), name: '', area: '', description: '', usage: '', versions: [] })} extraFilter={<Field label="상태"><select value={status} onChange={e => setStatus(e.target.value)}><option value="all">전체</option>{Object.entries(versionStatus).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></Field>} columns={[
    { key: 'name', label: '양식명', render: t => <button className="text-button" onClick={() => { setSelected(t.id); setVersionId('') }}>{t.name}</button> }, { key: 'area', label: '업무영역', render: t => t.area }, { key: 'version', label: '최근 Version', render: t => t.versions.at(-1)?.version || '미등록' }, { key: 'start', label: '적용 시작일', render: t => t.versions.at(-1)?.startsOn || '—' }, { key: 'status', label: '상태', render: t => <StatusBadge>{t.versions.at(-1) ? versionStatus[t.versions.at(-1)!.status] : 'Version 미등록'}</StatusBadge> }, { key: 'updated', label: '최근 수정일', render: t => t.versions.at(-1)?.modifiedAt.slice(0, 10) || '—' }, { key: 'usage', label: '사용처', render: t => t.usage },
  ]} />{feedback}{t && <section className="panel admin-detail"><div className="panel-heading"><h2>{t.name}</h2><button className="button primary" onClick={() => { setVersion({ id: crypto.randomUUID(), version: '', startsOn: today(), endsOn: '', status: 'stopped', required: [], optional: [], parserRef: v?.parserRef || 'mock-parser', modifiedAt: '' }); setRequired(v?.required.join(',') || ''); setOptional(v?.optional.join(',') || '') }}>새 Version 생성</button></div><p>{t.description}</p><Field label="Version 상세 조회"><select value={v?.id || ''} onChange={e => setVersionId(e.target.value)}>{t.versions.map(v => <option key={v.id} value={v.id}>{v.version} · {versionStatus[v.status]}</option>)}</select></Field>{v && <><DetailList items={[{ label: '필수 Column', value: v.required.join(', ') }, { label: '선택 Column', value: v.optional.join(', ') || '없음' }, { label: '적용기간', value: `${v.startsOn} ~ ${v.endsOn || '종료 미정'}` }, { label: '파싱 규칙 참조', value: v.parserRef }, { label: '사용상태', value: versionStatus[v.status] }]} /><div className="admin-actions"><button className="button secondary" onClick={() => download(t.id, 'Excel 양식', `template-${t.id}-${v.version}.csv`, [[...v.required, ...v.optional]])}>Template 다운로드 Mock</button><button className="button secondary" onClick={() => download(t.id, 'Excel 양식', `sample-${t.id}-${v.version}.csv`, [[...v.required, ...v.optional], [...v.required, ...v.optional].map(c => `시연_${c}`)])}>Sample 다운로드 Mock</button><button className="button secondary" disabled={v.status === 'expired'} onClick={() => save({ kind: 'versionStatus', templateId: t.id, versionId: v.id, status: v.status === 'active' ? 'stopped' : 'active' })}>{v.status === 'active' ? 'Version 중지' : 'Version 활성화'}</button></div></>}<h3>Version History · 이전 버전 보존</h3><DataTable caption="Version History" rows={t.versions} rowKey={v => v.id} columns={[{ key: 'version', label: 'Version', render: v => <button className="text-button" onClick={() => setVersionId(v.id)}>{v.version}</button> }, { key: 'period', label: '적용기간', render: v => `${v.startsOn} ~ ${v.endsOn || '종료 미정'}` }, { key: 'state', label: '상태', render: v => versionStatus[v.status] }]} /></section>}
    {draft && <Editor title="신규 양식 등록" onClose={() => setDraft(null)} onSave={() => { const error = save({ kind: 'template', value: draft }); if (!error) { setSelected(draft.id); setVersionId('') } return error }}>{(['name', 'area', 'description', 'usage'] as const).map((key, i) => <Field key={key} label={['양식명', '업무영역', '설명', '사용처'][i]}><input value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })} /></Field>)}</Editor>}
    {version && t && <Editor title="새 Version 생성" onClose={() => setVersion(null)} onSave={() => { const error = save({ kind: 'version', templateId: t.id, value: { ...version, required: split(required), optional: split(optional) } }); if (!error) setVersionId(version.id); return error }}><Field label="Version"><input value={version.version} onChange={e => setVersion({ ...version, version: e.target.value })} /></Field><Field label="적용 시작일"><input type="date" value={version.startsOn} onChange={e => setVersion({ ...version, startsOn: e.target.value })} /></Field><Field label="적용 종료일"><input type="date" value={version.endsOn} onChange={e => setVersion({ ...version, endsOn: e.target.value })} /></Field><Field label="필수 Column (쉼표 구분)"><textarea value={required} onChange={e => setRequired(e.target.value)} /></Field><Field label="선택 Column (쉼표 구분)"><textarea value={optional} onChange={e => setOptional(e.target.value)} /></Field><Field label="파싱 규칙 참조"><input value={version.parserRef} onChange={e => setVersion({ ...version, parserRef: e.target.value })} /></Field><p className="muted">새 Version은 중지 상태로 생성됩니다. 기존 Version을 보존하며 활성화 시 적용기간 중복을 검사합니다.</p></Editor>}
  </>
}
