import ExecutionDetail from './ExecutionDetail'
import { useState } from 'react'
import { useWorkflow } from '../../state/useWorkflow'
import DetailDrawer from '../../components/workflow/DetailDrawer'
import DataTable from '../../components/workflow/AssociationTable'
import { WorkflowKpis } from '../../components/workflow/WorkflowUI'
import { DetailList } from '../../components/common/ui'
import { Field } from '../../components/admin/AdminUI'
import WorkflowStatus from '../../components/workflow/WorkflowStatus'
import { won } from '../../data/workflowFormat'
import { displayText } from '../../data/workflowPresentation'
import type { AnomalyCase, StoreEventProduct } from '../../types/workflow'

export function AgriculturalDetail({storeId,mode,onClose,onProduct,onAdd,onSale,onMove,onRecover}:{storeId:string;mode:string;onClose:()=>void;onProduct:(p:StoreEventProduct)=>void;onAdd:()=>void;onSale:()=>void;onMove:()=>void;onRecover:()=>void}) {
 const w=useWorkflow(),[item,setItem]=useState(''),[history,setHistory]=useState(false),r=w.round
 if(!r)return null
 if(mode==='execution')return <ExecutionDetail storeId={storeId} onClose={onClose} onMove={onMove} onRecover={onRecover}/>
 const products=w.d.products.filter(p=>p.roundId===r.id&&p.storeId===storeId),tx=w.d.transactions.filter(t=>t.roundId===r.id&&t.storeId===storeId),allocated=w.d.allocations.find(a=>a.roundId===r.id&&a.storeId===storeId)?.amount||0,spent=tx.reduce((s,t)=>s+t.support,0),isProduct=mode==='event-products',representatives=w.d.representatives.filter(p=>r.official.items.includes(p.id)||products.some(v=>v.representativeId===p.id))
 return <DetailDrawer title={isProduct?'행사상품 상세':mode==='budget'?'점포 예산 상세':'점포 집행 상세'} context={`${w.storeName(storeId)} > ${r.name}`} onClose={onClose}>{w.feedback}
 {!isProduct&&<WorkflowKpis items={[["배정액",won(allocated)],['집행액',won(spent)],['잔액',won(allocated-spent)],['소진율',`${allocated?(spent/allocated*100).toFixed(1):0}%`]]} />}
 <div className="admin-actions">{isProduct?<button className="button secondary" onClick={onAdd}>판매상품 추가</button>:<><button className="button secondary" onClick={onMove}>추가배정 / 예산회수</button><button className="button secondary" onClick={()=>setHistory(!history)}>이력조회</button>{mode==='execution'&&<button className="button secondary" disabled={!products.some(p=>p.override!=='not-running'&&['confirmed','exception'].includes(p.status))} title="확정 행사상품이 있는 점포에 실적을 반영합니다" onClick={onSale}>실적 반영</button>}</>}</div>
 {isProduct?representatives.map(rep=><section className="panel" key={rep.id}><h3>{rep.name} · 대표품목 → 판매상품 {products.filter(p=>p.representativeId===rep.id).length}개</h3><DataTable caption={`${rep.name} 판매상품`} rows={products.filter(p=>p.representativeId===rep.id)} rowKey={p=>p.id} columns={[{key:'name',label:'실제 판매상품 / ADMS 상품코드',render:p=><><button className="text-button" onClick={()=>onProduct(structuredClone(p))}>{rep.name} → {p.name||'미제출'}</button><span className="cell-sub">{p.id}</span></>},{key:'price',label:'대표규격 / 판매예정가',render:p=>`${rep.unit} / ${won(p.price)}`},{key:'map',label:'Mapping / AI 가매핑',render:p=>`${!p.name?'미매핑':['confirmed','exception'].includes(p.status)?'확정':'검토 필요'} / ${p.source==='POS'&&p.status==='review'?'AI 후보':'없음'}`},{key:'photo',label:'사진 / 검증 결과',render:p=><>{p.photo?'첨부됨':'미첨부'}<span className="cell-sub">{p.override==='not-running'?'품목 미진행':!p.name?'상품명 필요':!p.photo?'사진 필요':!p.name.includes('농할')&&!p.override?'농할 문구 필요':p.price<=0?'가격 확인':'통과'}</span></>},{key:'exception',label:'예외처리',render:p=>p.override==='name-change'?'상품명 변경 예정':p.override==='not-running'?'해당 품목 미진행':'없음'},{key:'state',label:'확정상태',render:p=><><WorkflowStatus code={p.status}/><span className="cell-sub">{p.confirmedAt||'미확정'}</span></>},{key:'action',label:'업무',render:p=><button className="text-button" disabled={['confirmed','exception'].includes(p.status)} onClick={()=>w.save({kind:'confirmProduct',id:p.id})}>상품 확정</button>}]} /></section>):<section className="panel"><h3>품목별 집행 · 품목을 선택하면 거래를 조회합니다</h3><DataTable caption="품목별 집행" rows={representatives} rowKey={p=>p.id} columns={[{key:'item',label:'대표품목',render:p=><button className="text-button" aria-pressed={item===p.id} onClick={()=>setItem(p.id)}>{p.name}</button>},{key:'qty',label:'판매량',render:p=>tx.filter(t=>products.some(v=>v.id===t.productId&&v.representativeId===p.id)).reduce((s,t)=>s+t.quantity,0)},{key:'support',label:'지원금',render:p=>won(tx.filter(t=>products.some(v=>v.id===t.productId&&v.representativeId===p.id)).reduce((s,t)=>s+t.support,0))}]} /></section>}
 {!isProduct&&<section className="panel"><div className="panel-heading"><h3>{item?`${representatives.find(p=>p.id===item)?.name} > 거래내역`:'최근 거래'}</h3><button className="text-button" onClick={()=>setItem('')}>전체 품목</button></div><DataTable caption="실제 거래" rows={[...tx].reverse().filter(t=>!item||products.some(p=>p.id===t.productId&&p.representativeId===item))} rowKey={t=>t.id} columns={[{key:'tx',label:'거래 / 상품',render:t=>`${t.id} / ${products.find(p=>p.id===t.productId)?.name}`},{key:'qty',label:'수량 / 단가',render:t=>`${t.quantity} / ${won(t.price)}`},{key:'amount',label:'지원금',render:t=>won(t.support)},{key:'at',label:'거래시각',render:t=>t.at},{key:'valid',label:'검증',render:t=>t.valid?'통과':displayText(t.exclusion)}]} /></section>}
 {history&&<section className="panel"><DataTable caption="점포 예산 이력" rows={w.d.ledger.filter(l=>l.roundId===r.id&&l.storeId===storeId)} rowKey={l=>l.id} columns={[{key:'at',label:'시각 / 처리자',render:l=>`${l.at} / ${l.actor}`},{key:'type',label:'유형 / 사유',render:l=>`${displayText(l.type)} / ${displayText(l.reason)}`},{key:'amount',label:'변경 전 / 증감 / 변경 후',render:l=>`${won(l.before)} / ${won(l.delta)} / ${won(l.after)}`}]} /></section>}
 </DetailDrawer>
}
export function AnomalyDetail({value,onClose}:{value:AnomalyCase;onClose:()=>void}) {
 const w=useWorkflow(),[memo,setMemo]=useState(''),a=w.d.anomalies.find(a=>a.id===value.id)||value,tx=w.d.transactions.filter(t=>t.roundId===a.roundId&&t.storeId===a.storeId),allocated=w.d.allocations.find(v=>v.roundId===a.roundId&&v.storeId===a.storeId)?.amount||0
 const changes=w.data.changes.filter(c=>c.entity==='workflow:anomaly'&&(c.after as {target?:string}).target===a.id),original=(changes[0]?.before as {domain?:{anomalies?:AnomalyCase[]}})?.domain?.anomalies?.find(v=>v.id===a.id), detection=original?.note||value.note, last=tx.at(-1)
 return <DetailDrawer title="이상건 상세" context={`${w.storeName(a.storeId)} > ${displayText(a.kind)}`} onClose={onClose}>{w.feedback}<section className="panel admin-detail"><DetailList items={[{label:'점포 / 담당자 연락처',value:`${w.storeName(a.storeId)} / ${w.d.storeProfiles.find(p=>p.storeId===a.storeId)?.phone||'미등록'}`},{label:'탐지유형 / 근거',value:`${displayText(a.kind)} / ${displayText(detection)}`},{label:'발생시각',value:'원본에 발생시각 미등록'},{label:'최초 조치시각',value:changes[0]?.at||'조치 전'},{label:'최근 원천 거래시각',value:last?.at||'거래 없음'},{label:'관련 값 · 배정 / 집행 / 거래수',value:`${won(allocated)} / ${won(tx.reduce((s,t)=>s+t.support,0))} / ${tx.length}건`},{label:'현재 상태',value:<WorkflowStatus code={a.status}/>},{label:'처리메모',value:changes.length?displayText(a.note):'처리 전'}]} /><Field label="처리메모"><textarea value={memo} onChange={e=>setMemo(e.target.value)}/></Field><div className="admin-actions">{(a.status==='new'?[['checking','확인중']]:a.status==='checking'?[['resolved','조치완료'],['watching','관찰']]:a.status==='watching'?[['checking','확인중']]:[]).map(([status,label])=><button className="button secondary" key={status} disabled={!memo.trim()} onClick={()=>w.save({kind:'anomaly',id:a.id,value:a,status,reason:memo})}>{label}</button>)}</div></section><section className="panel"><DataTable caption="관련 품목 / 거래" rows={tx} rowKey={t=>t.id} columns={[{key:'tx',label:'거래 / 상품',render:t=>`${t.id} / ${w.d.products.find(p=>p.id===t.productId)?.name}`},{key:'at',label:'거래시각',render:t=>t.at},{key:'amount',label:'수량 / 지원금',render:t=>`${t.quantity} / ${won(t.support)}`}]} /></section><section className="panel"><DataTable caption="이상건 처리이력" rows={changes} rowKey={c=>c.id} columns={[{key:'at',label:'처리시각 / 담당자',render:c=>`${c.at} / ${w.data.accounts.find(a=>a.id===c.actorId)?.name}`},{key:'state',label:'처리 전 → 후',render:c=>{const before=(c.before as {domain?:{anomalies?:AnomalyCase[]}}).domain?.anomalies?.find(v=>v.id===a.id),after=(c.after as {values?:{anomalies?:AnomalyCase[]}}).values?.anomalies?.find(v=>v.id===a.id);return <><WorkflowStatus code={before?.status||'new'}/> → <WorkflowStatus code={after?.status||a.status}/></>}},{key:'memo',label:'처리메모',render:c=>displayText((c.after as {reason:string}).reason)}]} /></section></DetailDrawer>
}
