import { AgriculturalDetail, AnomalyDetail } from './AgriculturalDetails'
import PlanEditor from './PlanEditor'
import DataTable from '../../components/workflow/AssociationTable'
import WorkflowStatus from '../../components/workflow/WorkflowStatus'
import { displayText } from '../../data/workflowPresentation'
import { liveCapabilities } from '../../state/hubStore'
import { won, demoClock } from '../../data/workflowFormat'
import { useState } from 'react'
import { Check, Editor, Field } from '../../components/admin/AdminUI'
import { DetailDialog, DetailList, FilterBar, PageHeader } from '../../components/common/ui'
import { RoundSelect, WorkflowKpis } from '../../components/workflow/WorkflowUI'
import { useWorkflow } from '../../state/useWorkflow'
import type { StoreEventProduct, SaleTransaction, AnomalyCase } from '../../types/workflow'
const titles: Record<string, string> = { budget: '예산 관리', 'week-plan': '주차별 계획', 'event-products': '행사상품 등록현황', execution: '집행 실적', anomalies: '이상 감지' }
export default function AgriculturePage({ mode }: { mode: string }) {
  const w = useWorkflow(), [anomaly,setAnomaly]=useState<AnomalyCase|null>(null), [branchFilter,setBranchFilter]=useState(''), [query, setQuery] = useState(''), [selected, setSelected] = useState(''), [product, setProduct] = useState<StoreEventProduct | null>(null), [sale, setSale] = useState<SaleTransaction | null>(null), [planSource,setPlanSource]=useState<'AT 연계'|'협회 직접 등록'|null>(null), [dialog, setDialog] = useState(''), [amount, setAmount] = useState(100000), [reason, setReason] = useState(''), [confirmed, setConfirmed] = useState(false), [weights, setWeights] = useState(''), [error, setError] = useState('')
  const r = w.round, allocations = w.d.allocations.filter(a => a.roundId === r?.id), products = w.d.products.filter(p => p.roundId === r?.id), transactions = w.d.transactions.filter(t => t.roundId === r?.id), budget = w.d.annualBudgets.find(a => a.operatorId === w.operatorId && a.businessId === w.businessId)
  const roundStores = w.stores.filter(s => allocations.some(a=>a.storeId===s.id) || products.some(p=>p.storeId===s.id) || (r && r.endsOn>=demoClock.slice(0,10) && w.data.participations.some(p=>p.businessId===w.businessId && p.storeId===s.id && p.status==='active')))
  const storeRows = roundStores.filter(s=>s.name.includes(query) && (!branchFilter || w.branchName(s.id)===branchFilter)), assigned = (id: string) => allocations.find(a => a.storeId === id)?.amount || 0
  const openMove = (storeId: string) => { setSelected(storeId); setDialog('budget'); setReason(''); setAmount(100000) }
  return <><PageHeader title={titles[mode]} eyebrow="AGRICULTURAL OPERATIONS" description="사업·주차·점포별 공통 데이터와 원장 기준으로 계획, 준비, 집행을 연결합니다." actions={mode === 'week-plan' ? <div className="admin-actions"><button className="button secondary" onClick={()=>setPlanSource('AT 연계')}>AT 계획 가져오기</button><button className="button primary" onClick={()=>setPlanSource('협회 직접 등록')}>직접 등록</button></div> : mode === 'budget' ? <button className="button secondary" onClick={() => { setDialog('annual'); setAmount(budget?.total || 0); setReason('') }}>연간 예산 조정</button> : undefined} />{w.feedback}{r ? <><FilterBar><RoundSelect rounds={w.rounds} selected={r.id} onSelect={id => { w.select('round', id); setSelected(''); setAnomaly(null) }} /><Field label="점포 검색"><input value={query} onChange={e => setQuery(e.target.value)} /></Field><Field label="지회"><select value={branchFilter} onChange={e=>setBranchFilter(e.target.value)}><option value="">전체 지회</option>{w.branches.map(b=><option key={b.id} value={b.name}>{b.name}</option>)}</select></Field><WorkflowStatus code={r.status} /></FilterBar><WorkflowKpis items={[["주차 예산", won(r.operating.budget)], ['집행액', won(w.execution(r.id).amount)], ['집행률', `${(w.execution(r.id).amount / r.operating.budget * 100).toFixed(1)}%`], ['참여점포', roundStores.length], ['예비비 잔액', won(w.reserve(r.id))], ['소진임박 점포', allocations.filter(a=>a.amount>0 && w.execution(r.id,a.storeId).amount/a.amount>=.8).length]]} />
    {mode==='budget' && <details className="panel association-annual"><summary>연간 예산 현황 <span>총예산 {won(budget?.total || 0)} · 펼쳐서 조회</span></summary><DetailList items={[{label:'연간 총예산',value:won(budget?.total || 0)},{label:'가용예산',value:won((budget?.total || 0)-w.rounds.reduce((s,r)=>s+r.operating.budget,0)+w.d.ledger.filter(l=>l.operatorId===w.operatorId && l.businessId===w.businessId && l.type.startsWith('최종불인정')).reduce((s,l)=>s+l.delta,0))},{label:'누적 배정',value:won(w.d.allocations.filter(a=>w.rounds.some(r=>r.id===a.roundId)).reduce((s,a)=>s+a.amount,0))},{label:'누적 집행',value:won(w.d.transactions.filter(t=>w.rounds.some(r=>r.id===t.roundId)).reduce((s,t)=>s+t.support,0))}]} /></details>}
    {mode === 'week-plan' && <section className="panel admin-detail"><h2>공식 계획정보</h2><DetailList items={[{ label: '행사기간', value: `${r.startsOn}~${r.endsOn}` }, { label: '대표품목', value: r.official.items.map(id => w.d.representatives.find(p => p.id === id)?.name).join(', ') }, { label: '정부 할인율 / 개인한도', value: `${r.official.discount}% / ${won(r.official.personalLimit)}` }, { label: '운영조건 / 출처', value: `${displayText(r.official.conditions)} / ${r.official.source.includes('협회')?'협회 직접 등록':r.official.source.includes('AT')?'AT 연계':displayText(r.official.source)}` }]} /><h3>협회 운영정보</h3><DetailList items={[{ label: '주차 예산 / 예비비', value: `${won(r.operating.budget)} / ${r.operating.reserveRate}%` }, { label: '배분방식', value: r.operating.mode === 'direct' ? '협회→점포' : '협회→지회→점포' }, { label: '상품 등록 마감', value: r.operating.deadline }]} /><button className="button primary" disabled={r.status !== 'draft'} onClick={() => w.save({ kind: 'confirmRound', id: r.id })}>주차 계획 확정</button></section>}
    {['budget', 'execution', 'event-products'].includes(mode) && <section className="panel"><DataTable caption={titles[mode]} rows={storeRows} rowKey={s => s.id} columns={[{ key: 'store', label: '점포 / 지회', render: s => <button className="text-button" onClick={() => setSelected(s.id)}>{s.name}<span className="cell-sub">{w.branchName(s.id)}</span></button> }, ...(['budget','execution'].includes(mode)?[{key:'assigned',label:'배정액',render:(s: typeof w.stores[number])=>won(assigned(s.id))},{key:'spent',label:'집행액',render:(s:typeof w.stores[number])=>won(w.execution(r.id,s.id).amount)},{key:'balance',label:'잔액',render:(s:typeof w.stores[number])=>won(assigned(s.id)-w.execution(r.id,s.id).amount)},{key:'rate',label:'소진율',render:(s:typeof w.stores[number])=><span className="association-rate">{assigned(s.id)?(w.execution(r.id,s.id).amount/assigned(s.id)*100).toFixed(1):0}%</span>},{key:'state',label:'상태',render:(s:typeof w.stores[number])=><WorkflowStatus code={!w.execution(r.id,s.id).amount?'무실적':w.execution(r.id,s.id).amount>=assigned(s.id)?'소진':w.execution(r.id,s.id).amount/assigned(s.id)>=.8?'소진임박':'진행중'} />}]:[]), ... (mode==='event-products' ? [{ key: 'products', label: '등록 / 확정 / 예외', render: (s:typeof w.stores[number]) => { const items = products.filter(p => p.storeId === s.id); return `${items.length} / ${items.filter(p => ['confirmed', 'exception'].includes(p.status)).length} / ${items.filter(p => p.status === 'exception').length}` } }, { key: 'mapping', label: '미매핑 / AI 가매핑', render: (s:typeof w.stores[number]) => { const items = products.filter(p => p.storeId === s.id); return `${items.filter(p => !p.name).length} / ${items.filter(p => p.source === "POS" && p.status === "review").length}` } },  ] : []), { key: 'time', label: mode==='event-products'?'확정시간':'최근 집계', render: (s:typeof w.stores[number]) => (mode==='event-products'?products.filter(p=>p.storeId===s.id).at(-1)?.confirmedAt:transactions.filter(t=>t.storeId===s.id).at(-1)?.at) || '미집계' }, {key:'actions',label:'업무',render:s=>mode==='event-products'?<button className="text-button" onClick={()=>setSelected(s.id)}>상세 / 확인</button>:<button className="text-button" onClick={()=>openMove(s.id)}>추가배정 / 회수</button>}]} />{mode === 'budget' && !transactions.length && !w.d.claims.some(c=>w.d.batches.some(b=>b.id===c.batchId && b.roundIds.includes(r.id))) && <div className="admin-actions"><button className="button primary" onClick={() => w.save({ kind: 'allocate', id: r.id, method: 'equal' })}>균등배분</button><button className="button secondary" onClick={() => { setWeights(w.stores.map(s => `${s.id},1`).join('\n')); setDialog('weights'); setError('') }}>가중치 Excel 가져오기</button></div>}{mode === 'execution' && r.status==='executing' && <div className="admin-actions"><Check label="집행 실적 마감을 확인했습니다" checked={confirmed} onChange={setConfirmed} /><button className="button secondary" onClick={() => w.save({ kind: 'endRound', id: r.id, confirmed })}>실적 마감</button></div>}</section>}
    {selected && ['event-products','execution','budget'].includes(mode) && <AgriculturalDetail key={r.id+selected+mode} storeId={selected} mode={mode} onClose={()=>setSelected('')} onProduct={setProduct} onMove={()=>openMove(selected)} onRecover={()=>{openMove(selected);setAmount(-100000)}} onAdd={()=>setProduct({id:crypto.randomUUID(),roundId:r.id,storeId:selected,representativeId:r.official.items[0],name:'',price:10000,photo:false,override:'',source:'manual',status:'draft',confirmedAt:''})} onSale={()=>{const p=products.find(p=>p.storeId===selected&&p.override!=='not-running'&&['confirmed','exception'].includes(p.status));if(!p){setError('확정 상품이 필요합니다.');return}setSale({id:'',roundId:r.id,storeId:selected,productId:p.id,at:r.startsOn+'T09:00',quantity:1,price:p.price,support:2000,source:'manual',valid:true,exclusion:''})}}/>}
    {anomaly && <AnomalyDetail value={anomaly} onClose={()=>setAnomaly(null)}/>}
    {mode === 'anomalies' && <section className="panel"><DataTable caption="이상감지" rows={[...w.d.anomalies.filter(a => a.roundId === r.id), ...storeRows.filter(s => !w.execution(r.id, s.id).amount && !w.d.anomalies.some(a=>a.roundId===r.id&&a.storeId===s.id&&a.kind==='무실적')).map(s => ({ id: `no-sales-${r.id}-${s.id}`, roundId: r.id, storeId: s.id, kind: '무실적', status: 'new' as const, note: '해당 주차의 집행 자료에 거래 없음', source: 'cumulative' as const }))]} rowKey={a => a.id} columns={[{ key: 'store', label: '점포 / 담당자', render: a => `${w.storeName(a.storeId)} / ${w.d.storeProfiles.find(p => p.storeId === a.storeId)?.phone}` }, { key: 'kind', label: '유형 / 근거', render: a => `${displayText(a.kind)} / ${displayText(a.note)}` }, { key: 'state', label: '상태 / 출처', render: a => <><WorkflowStatus code={a.status} /><span className="cell-sub">{displayText(a.source)}</span></> }, { key: 'action', label: '조치', render: a => <button className="text-button" onClick={()=>setAnomaly(a)}>상세 / 조치</button> }]} /></section>}
    {mode === 'budget' && <section className="panel admin-detail"><h2>예비비 / 반환 원장</h2><p>연간 총예산 {won(budget?.total || 0)} · 주차 확정예산 {won(w.rounds.reduce((s, r) => s + r.operating.budget, 0))} · 최종 불인정 환원 {won(w.d.ledger.filter(l => l.operatorId === w.operatorId && l.businessId === w.businessId && l.type.startsWith('최종불인정')).reduce((s, l) => s + l.delta, 0))}</p><DataTable caption="원장" rows={w.d.ledger.filter(l => l.operatorId === w.operatorId && l.businessId === w.businessId)} rowKey={l => l.id} columns={[{ key: 'at', label: '시각 / 유형', render: l => `${l.at} / ${displayText(l.type)}` }, { key: 'store', label: '점포', render: l => l.storeId ? w.storeName(l.storeId) : '주차 전체' }, { key: 'balance', label: '변경전 / 증감 / 변경후', render: l => `${won(l.before)} / ${won(l.delta)} / ${won(l.after)}` }, { key: 'reason', label: '사유 / 처리자', render: l => `${displayText(l.reason)} / ${displayText(l.actor)}` }]} /></section>}</> : <p className="notice-box">선택 사업에 농할 주차가 없습니다.</p>}
    {planSource && <PlanEditor source={planSource} onClose={()=>setPlanSource(null)} />}
    {product && !['confirmed','exception'].includes(product.status) && <Editor title="행사상품 입력 / 확인" onClose={() => setProduct(null)} onSave={() => w.save({ kind: 'product', value: product })}><Field label="대표상품"><select value={product.representativeId} onChange={e => setProduct({ ...product, representativeId: e.target.value })}>{w.d.representatives.map(p => <option key={p.id} value={p.id}>{displayText(p.name)}</option>)}</select></Field><Field label="실제 판매상품명"><input value={product.name} onChange={e => setProduct({ ...product, name: e.target.value })} /></Field><Field label="판매가"><input type="number" value={product.price} onChange={e => setProduct({ ...product, price: Number(e.target.value) })} /></Field><Field label="입력 경로"><select value={product.source} onChange={e => setProduct({ ...product, source: e.target.value as typeof product.source })}><option>POS</option><option value="manual">직접입력</option><option>Excel</option></select></Field><Check label="대표상품 사진 첨부" checked={product.photo} onChange={photo => setProduct({ ...product, photo })} /><Field label="예외 처리 사유"><select value={product.override} onChange={e => setProduct({ ...product, override: e.target.value as typeof product.override })}><option value="">예외 없음</option><option value="name-change">행사 시작 전 상품명 변경 예정</option><option value="not-running">해당 품목 미진행</option></select></Field><div className="full-width admin-actions"><button type="button" className="button secondary" disabled={!w.data.hub.connections.some(c => c.storeId === product.storeId && liveCapabilities(w.data.hub, c).some(v => v.id === "product"))} onClick={() => setProduct({ ...product, name: `농할 국내산 ${w.d.representatives.find(v => v.id === product.representativeId)?.name} 시연규격`, price: 10000, source: "POS" })}>POS 상품 수집 / AI 가매핑</button><button type="button" className="button secondary" onClick={() => setProduct({ ...product, name: "농할 국내산 사과 1kg", price: 8000, source: "Excel" })}>내장 Excel 예시 미리보기</button></div><p className="full-width">수집한 후보를 확인한 후 상품명, 가격과 사진을 확정하세요.</p></Editor>}
    {product && ['confirmed','exception'].includes(product.status) && <DetailDialog title="확정 행사상품 상세" onClose={()=>setProduct(null)}><WorkflowStatus code={product.status} /><DetailList items={[{label:'실제 상품명',value:product.name},{label:'대표품목',value:w.d.representatives.find(v=>v.id===product.representativeId)?.name},{label:'판매가',value:won(product.price)},{label:'사진',value:product.photo?'첨부됨':'미첨부'},{label:'예외 사유',value:product.override==='name-change'?'상품명 변경 예정':product.override==='not-running'?'품목 미진행':'없음'},{label:'확정시각',value:product.confirmedAt}]} /></DetailDialog>}
    {sale && <Editor title="집행 실적 반영" onClose={() => setSale(null)} onSave={() => w.save({ kind: 'sale', value: sale })}><Field label="확정 행사상품"><select value={sale.productId} onChange={e => setSale({ ...sale, productId: e.target.value, price: products.find(p => p.id === e.target.value)?.price || 0 })}>{products.filter(p => p.storeId === sale.storeId && p.override !== 'not-running' && ['confirmed', 'exception'].includes(p.status)).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="수량"><input type="number" value={sale.quantity} onChange={e => setSale({ ...sale, quantity: Number(e.target.value) })} /></Field><Field label="지원금"><input type="number" value={sale.support} onChange={e => setSale({ ...sale, support: Number(e.target.value) })} /></Field><Field label="거래시각"><input type="datetime-local" value={sale.at} onChange={e => setSale({ ...sale, at: e.target.value })} /></Field></Editor>}
    {['budget', 'annual'].includes(dialog) && <Editor title={dialog === 'annual' ? '연간 예산 조정' : '점포 추가배정 / 미사용 회수'} onClose={() => setDialog('')} onSave={() => w.save({ kind: dialog === 'annual' ? 'annual' : 'budgetMove', id: r?.id, storeId: selected, amount, reason })}><Field label={dialog === 'annual' ? '연간 총예산' : '배정 증감액 (회수는 음수)'}><input type="number" value={amount} onChange={e => setAmount(Number(e.target.value))} /></Field><Field label="사유"><textarea value={reason} onChange={e => setReason(e.target.value)} /></Field></Editor>}
    {dialog === 'weights' && r && <DetailDialog title="가중치 Excel 가져오기" onClose={() => setDialog('')}><p>내장 예시 또는 로컬 CSV로 가중치를 미리보고 적용합니다. 형식: 점포ID,가중치</p><input aria-label="가중치 CSV 파일" type="file" accept=".csv" onChange={async e => { const file = e.target.files?.[0]; if (file) setWeights(await file.text()) }} /><Field label="가중치 미리보기"><textarea value={weights} onChange={e => setWeights(e.target.value)} /></Field>{error && <p role="alert">{error}</p>}<button className="button primary" onClick={() => { const rows = weights.trim().split('\n').map(line => line.trim().split(',')); if (rows.some(row => row.length !== 2 || !w.stores.some(s => s.id === row[0])) || new Set(rows.map(row => row[0])).size !== rows.length) { setError('점포ID와 가중치 두 열을 중복 없이 입력해 주세요.'); return } const result = w.save({ kind: 'allocate', id: r.id, method: 'Excel', value: Object.fromEntries(rows.map(([id, value]) => [id, Number(value)])) }); if (!result) setDialog(''); else setError(result) }}>검증 후 배분 반영</button></DetailDialog>}
  </>
}
