import { navigationFor } from '../../access/policy'
import { won, demoClock } from '../../data/workflowFormat'
import { Link } from 'react-router'
import { DataTable, PageHeader } from '../../components/common/ui'
import { WorkflowKpis } from '../../components/workflow/WorkflowUI'
import { useWorkflow } from '../../state/useWorkflow'
import WorkflowStatus from '../../components/workflow/WorkflowStatus'
export default function AssociationHome() {
 const w=useWorkflow(), today=demoClock.slice(0,10), r=w.rounds.find(r=>r.startsOn<=today&&r.endsOn>=today), next=w.rounds.filter(r=>r.startsOn>today).sort((a,b)=>a.startsOn.localeCompare(b.startsOn))[0], products=w.d.products.filter(p=>p.roundId===next?.id), dues=w.d.dues.filter(d=>d.operatorId===w.operatorId&&d.month==='2026-10'), total=dues.reduce((s,d)=>s+d.amount,0), paid=w.d.receipts.filter(v=>dues.some(d=>d.id===v.dueId)).reduce((s,v)=>s+v.amount,0), batchIds=w.batches.map(b=>b.id)
 const available=w.account?navigationFor(w.account,w.businessId,w.data).map(p=>p.id):[], publicIntegrations=w.d.integrations.filter(i=>i.operatorId===w.operatorId&&i.businessId===w.businessId), pending=w.d.applications.filter(a=>a.operatorId===w.operatorId&&['pending','reviewing'].includes(a.status)).length
 const issues=[{title:`가입 심사 대기 ${pending}건`,route:'membership-review'},{title:`차주 미확정 상품 ${products.filter(p=>!['confirmed','exception'].includes(p.status)).length}건`,route:`event-products?round=${next?.id||''}`},{title:`이상감지 ${w.d.anomalies.filter(a=>w.rounds.some(r=>r.id===a.roundId)&&a.status==='new').length}건`,route:'anomalies'},{title:`정산 / 재심사 처리 ${w.d.rejections.filter(c=>batchIds.includes(c.batchId)&&!['approved','rejected','accepted'].includes(c.status)).length}건`,route:'appeals'},{title:`지급 대기 ${w.d.payouts.filter(p=>batchIds.includes(p.batchId)&&p.status!=='paid').length}건`,route:'settlement'}].filter(i=>available.includes(i.route.split('?')[0]))
 return <div className="association-screen"><PageHeader eyebrow="ASSOCIATION OPERATIONS" title="운영기관 홈" description={`${w.d.settings.find(s=>s.operatorId===w.operatorId)?.brand||w.organization?.name} · ${w.business?.name}`} /><section className="panel association-priority"><h2>처리 필요 / 주의</h2><div className="hub-flow">{issues.map(i=><Link key={i.route} to={`/p/${i.route}`}>{i.title}</Link>)}</div></section><WorkflowKpis items={[["전체 회원사",w.companies.length],['전체 점포',w.stores.length],['가입 심사 대기',pending],['관리자 승인대기',w.data.accounts.filter(a=>a.status==='pending'&&w.companies.some(c=>c.id===a.companyId)).length],['당월 수납률',`${total?(paid/total*100).toFixed(1):0}%`]]} />
 {available.includes('week-plan')?<><div className="association-section-title"><h2>금주 농할</h2>{r&&<WorkflowStatus code={r.status} />}</div><WorkflowKpis items={[["금주 예산",won(r?.operating.budget||0)],['집행액',won(r?w.execution(r.id).amount:0)],['집행률',`${r?(w.execution(r.id).amount/r.operating.budget*100).toFixed(1):0}%`],['참여 점포',new Set(w.d.allocations.filter(a=>a.roundId===r?.id).map(a=>a.storeId)).size],['예비비',won(r?w.reserve(r.id):0)]]} /><section className="panel admin-detail"><div className="panel-heading"><h2>차주 준비</h2><Link to={`/p/event-products?round=${next?.id||''}`}>등록 현황 확인</Link></div><p>{next?.startsOn} ~ {next?.endsOn} · 등록 마감 {next?.operating.deadline||'해당 없음'}</p><DetailRow label="등록 준비" value={`확정 ${products.filter(p=>['confirmed','exception'].includes(p.status)).length} / 미완료 ${products.filter(p=>!['confirmed','exception'].includes(p.status)).length} / 예외확정 ${products.filter(p=>p.status==='exception').length}`} /><DetailRow label="마감까지 남은 시간" value={`${next?Math.max(0,Math.floor((Date.parse(next.operating.deadline)-Date.parse(demoClock))/3600000)):0}시간`} /><DetailRow label="정산대기" value={`${w.batches.filter(b=>b.status!=='final').length}차수`} /></section></>:<><h2>알뜰소비플랫폼 운영</h2><WorkflowKpis items={[["참여 점포",w.stores.filter(s=>w.data.participations.some(p=>p.businessId===w.businessId&&p.storeId===s.id&&p.status==='active')).length],['현재 공개 상품',publicIntegrations.reduce((n,i)=>n+i.currentProductIds.length,0)],['연동 오류',publicIntegrations.filter(i=>i.error).length],['게시 준비 전단',w.d.flyers.filter(f=>f.operatorId===w.operatorId&&f.businessId===w.businessId&&f.status!=='published').length]]} /><section className="panel admin-detail"><h2>공개 데이터 처리</h2><div className="hub-flow">{available.filter(id=>['public-data','flyers','public-history'].includes(id)).map(id=><Link key={id} to={`/p/${id}`}>{id==='public-data'?'공개 상품 확인':id==='flyers'?'전단 게시 준비':'연동 오류 / 재처리'}</Link>)}</div></section></>}
 <section className="panel"><div className="association-section-title"><h2>최근 공지</h2><Link to="/p/notices">전체 보기</Link></div><DataTable caption="최근 공지" rows={w.d.notices.filter(n=>n.operatorId===w.operatorId&&n.kind==='notice'&&n.active).slice(-5).reverse()} rowKey={n=>n.id} columns={[{key:'title',label:'공지',render:n=><Link to="/p/notices">{n.important?'중요 · ':''}{n.title}</Link>},{key:'period',label:'게시기간',render:n=>`${n.startsOn} ~ ${n.endsOn}`}]} /></section></div>
}
function DetailRow({label,value}:{label:string;value:string}) { return <p className="association-meta"><span>{label}</span><strong>{value}</strong></p> }
