import { PageHeader } from '../../components/common/ui'
import { displayText } from '../../data/workflowPresentation'
import { useState } from 'react'
import { useWorkflow } from '../../state/useWorkflow'
import { Field } from '../../components/admin/AdminUI'
import AssociationList from '../../components/workflow/AssociationList'
import WorkflowStatus from '../../components/workflow/WorkflowStatus'
import { WorkflowKpis } from '../../components/workflow/WorkflowUI'
import { companyFeeSummary } from '../../data/associationSummary'
export default function CompanyList({onSelect}:{onSelect:(id:string)=>void}) {
 const w=useWorkflow(), [branch,setBranch]=useState(''), [pos,setPos]=useState(''), [participation,setParticipation]=useState('')
 const participating=(id:string)=>w.stores.some(s=>s.companyId===id && w.data.participations.some(p=>p.storeId===s.id && p.businessId==='nonghal-2026' && p.status==='active'))
 const rows=w.companies.filter(c=>(!branch||w.data.organizations.find(o=>o.id===c.organizationId)?.parentId===branch)&&(!pos||w.stores.some(s=>s.companyId===c.id && (pos==='none'?!s.posId:s.posId===pos)))&&(!participation||participating(c.id)===(participation==='active')))
 return <><PageHeader eyebrow="ASSOCIATION OPERATIONS" title="회원사 관리" description="회원사 기본정보, 점포 및 사업 참여 현황을 함께 확인합니다." /><WorkflowKpis items={[["전체 회원사",w.companies.length],['전체 점포',w.stores.length],['농할 참여 회원사',w.companies.filter(c=>participating(c.id)).length],['미참여 회원사',w.companies.filter(c=>!participating(c.id)).length],['정상 연동 점포',w.stores.filter(s=>s.posConnectionStatus==='active').length]]} /><AssociationList showHeader={false} title="회원사 관리" description="회원사 기본정보, 점포 및 사업 참여 현황을 함께 확인합니다." rows={rows} rowKey={c=>c.id} searchText={c=>`${c.legalName} ${c.representativeName} ${w.d.companyProfiles.find(p=>p.companyId===c.id)?.registrationNo}`} extraFilter={<><Field label="지회"><select value={branch} onChange={e=>setBranch(e.target.value)}><option value="">전체 지회</option>{w.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><Field label="POS"><select value={pos} onChange={e=>setPos(e.target.value)}><option value="">전체 POS</option><option value="none">미지정</option>{w.data.hub.poses.map(p=><option key={p.id} value={p.id}>{displayText(p.name)}</option>)}</select></Field><Field label="농할 참여"><select value={participation} onChange={e=>setParticipation(e.target.value)}><option value="">전체</option><option value="active">참여</option><option value="none">미참여</option></select></Field></>} columns={[{key:'name',label:'회원사명',render:c=><button className="text-button" onClick={()=>onSelect(c.id)}>{c.legalName}</button>},{key:'owner',label:'대표자',render:c=>c.representativeName},{key:'registration',label:'사업자번호',render:c=>w.d.companyProfiles.find(p=>p.companyId===c.id)?.registrationNo},{key:'branch',label:'지회',render:c=>w.data.organizations.find(o=>o.id===w.data.organizations.find(o=>o.id===c.organizationId)?.parentId)?.name||'직할'},{key:'stores',label:'점포수',render:c=>w.stores.filter(s=>s.companyId===c.id).length},{key:'pos',label:'POS',render:c=>[...new Set(w.stores.filter(s=>s.companyId===c.id).map(s=>displayText(w.data.hub.poses.find(p=>p.id===s.posId)?.name||'미지정')))].join(' / ')},{key:'participation',label:'농할 참여',render:c=><WorkflowStatus code={participating(c.id)?'참여':'미참여'} />},{key:'fee',label:'회비 상태',render:c=><WorkflowStatus code={companyFeeSummary(w.data,c.id).status} />},{key:'state',label:'상태',render:c=><WorkflowStatus code={!w.data.organizations.find(o=>o.id===c.organizationId)?.active?'휴면':w.stores.some(s=>s.companyId===c.id && w.data.participations.some(p=>p.storeId===s.id && p.status==='stopping'))?'탈퇴 예정':'정상'} />}]} /></>
}
