import { useMemo, useState } from 'react'
import { useWorkflow } from '../../state/useWorkflow'
import { executionView } from '../../data/executionView'
import { won } from '../../data/workflowFormat'
import { displayText } from '../../data/workflowPresentation'
import DetailDrawer from '../../components/workflow/DetailDrawer'
import { DataTable } from '../../components/common/ui'
import type { PosSaleRow } from '../../types/executionView'

export default function ExecutionDetail({storeId,onClose,onMove,onRecover}:{storeId:string;onClose:()=>void;onMove:()=>void;onRecover:()=>void}) {
 const w=useWorkflow(),[item,setItem]=useState(''),[history,setHistory]=useState(false),[page,setPage]=useState(1),[size,setSize]=useState(20),r=w.round
 const rows=useMemo(()=>executionView(w.d.transactions.filter(t=>t.roundId===r?.id&&t.storeId===storeId),w.d.products,storeId),[w.d.transactions,w.d.products,r?.id,storeId])
 if(!r)return null
 const allocated=w.d.allocations.find(a=>a.roundId===r.id&&a.storeId===storeId)?.amount||0,spent=w.execution(r.id,storeId).amount,filtered=rows.filter(t=>!item||t.representativeId===item).sort((a,b)=>b.at.localeCompare(a.at)||b.number.localeCompare(a.number)),max=Math.max(1,Math.ceil(filtered.length/size)),current=Math.min(page,max),representatives=w.d.representatives.filter(p=>r.official.items.includes(p.id)||rows.some(t=>t.representativeId===p.id))
 const summaries=representatives.map(p=>{const group=rows.filter(t=>t.representativeId===p.id);return {...p,products:new Set(group.map(t=>t.productCode)).size,count:group.length,quantity:group.reduce((s,t)=>s+t.quantity,0),gross:group.reduce((s,t)=>s+t.gross,0),ownDiscount:group.reduce((s,t)=>s+t.ownDiscount,0),support:group.reduce((s,t)=>s+t.support,0),net:group.reduce((s,t)=>s+t.net,0)}})
 const money=(v:number)=><span className={`sale-number${v<0?' negative':''}`}>{v.toLocaleString('ko-KR')}</span>
 return <DetailDrawer title="점포 예산/판매 상세" context={`${w.storeName(storeId)} > ${r.name}`} onClose={onClose}><div className="execution-detail">
 <dl className="execution-summary">{[['배정액',won(allocated)],['집행액',won(spent)],['잔액',won(allocated-spent)],['소진율',`${allocated?(spent/allocated*100).toFixed(1):0}%`],['총 거래건수',`${rows.length.toLocaleString()}건`],['최종 집계시각',rows.reduce((latest,t)=>t.at>latest?t.at:latest,'')||'미집계']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
 <div className="execution-toolbar"><p>금액 단위: 원 · 취소/반품은 음수로 표시</p><div className="admin-actions"><button className="button secondary" onClick={onMove}>추가배정</button><button className="button secondary" onClick={onRecover}>예산회수</button><button className="button secondary" aria-expanded={history} onClick={()=>setHistory(!history)}>이력조회</button></div></div>
 <section className="panel execution-table"><h3>품목별 집행 Summary</h3><DataTable caption="품목별 집행" rows={summaries} rowKey={p=>p.id} columns={[{key:'item',label:'대표품목',render:p=><button className="text-button" aria-pressed={item===p.id} onClick={()=>{setItem(item===p.id?'':p.id);setPage(1)}}>{p.name}</button>},{key:'products',label:'판매상품 수',render:p=>money(p.products)},{key:'qty',label:'판매수량',render:p=>money(p.quantity)},{key:'gross',label:'정상판매금액',render:p=>money(p.gross)},{key:'own',label:'자체할인액',render:p=>money(p.ownDiscount)},{key:'support',label:'농할지원금',render:p=>money(p.support)},{key:'net',label:'순결제금액',render:p=>money(p.net)},{key:'count',label:'거래건수',render:p=>money(p.count)}]}/></section>
 <section className="panel execution-table"><div className="panel-heading"><h3>{item?`${representatives.find(p=>p.id===item)?.name} > 거래내역`:'판매 거래내역'}</h3><button className="text-button" onClick={()=>{setItem('');setPage(1)}}>전체 품목</button></div><div className="execution-sale-table"><DataTable caption="실제 거래" rows={filtered.slice((current-1)*size,current*size)} rowKey={t=>t.number} columns={[
 {key:'at',label:'거래일시',render:t=>t.at},{key:'store',label:'점포코드',render:t=>t.storeCode},{key:'terminal',label:'POS번호',render:t=>t.terminal},{key:'customer',label:'회원/고객 ID',render:t=>t.customer},{key:'number',label:'거래번호',render:t=>t.number},{key:'receipt',label:'영수증번호',render:t=>t.receipt},{key:'productCode',label:'상품코드',render:t=>t.productCode},{key:'name',label:'상품명',render:t=><span className="sale-product-name">{t.productName}</span>},{key:'qty',label:'수량',render:t=>money(t.quantity)},{key:'price',label:'정상판매가',render:t=>money(t.price)},{key:'own',label:'자체할인금',render:t=>money(t.ownDiscount)},{key:'support',label:'농할지원금',render:t=>money(t.support)},{key:'net',label:'순결제금액',render:t=>money(t.net)},{key:'kind',label:'정상/취소/반품',render:t=><span className={`sale-kind ${t.kind==='정상'?'':'sale-reversed'}`}>{t.kind}</span>},{key:'original',label:'원거래번호',render:t=>t.original||'—'},{key:'validation',label:'검증상태',render:(t:PosSaleRow)=><span className={t.validation.startsWith('정상')?'':'sale-warning'}>{displayText(t.validation)}</span>}]} /></div>
 <div className="association-pagination"><span>총 {filtered.length.toLocaleString()}건 · {current} / {max}페이지</span><select aria-label="거래 페이지당 표시" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option value={20}>20개씩</option><option value={50}>50개씩</option></select><button className="button secondary" disabled={current===1} onClick={()=>setPage(current-1)}>이전</button><button className="button secondary" disabled={current===max} onClick={()=>setPage(current+1)}>다음</button></div><p className="execution-data-note">거래번호·POS·회원정보·자체할인은 시연용 판매 상세입니다. 집계 원본을 단위 판매로 펼쳤으며 취소/반품 예시는 원거래와 상계됩니다. 예산·집행·청구 원본에는 반영하지 않습니다.</p></section>
 {history&&<section className="panel execution-table"><h3>점포 예산 변경 이력</h3><DataTable caption="점포 예산 이력" rows={w.d.ledger.filter(l=>l.roundId===r.id&&l.storeId===storeId)} rowKey={l=>l.id} columns={[{key:'at',label:'시각 / 처리자',render:l=>`${l.at} / ${l.actor}`},{key:'type',label:'유형 / 사유',render:l=>`${displayText(l.type)} / ${displayText(l.reason)}`},{key:'amount',label:'변경 전 / 증감 / 변경 후',render:l=>`${won(l.before)} / ${won(l.delta)} / ${won(l.after)}`}]} /></section>}
 </div></DetailDrawer>
}
