import {CompanyDetail,BranchDetail} from './OrganizationDetails'
import AdminList from '../../components/workflow/AssociationList'
import CompanyList from './CompanyList'
import FeesPage from './FeesPage'
import WorkflowStatus from '../../components/workflow/WorkflowStatus'
import { displayText } from '../../data/workflowPresentation'
import { useState } from 'react'
import { Active, Check, Editor, Field } from '../../components/admin/AdminUI'
import { DetailDialog, DetailList } from '../../components/common/ui'
import { useWorkflow } from '../../state/useWorkflow'
import { statuses } from '../../types/status'

export default function MembershipPage({ mode }: { mode: string }) {
  const [partyStoreIds, setPartyStoreIds] = useState<string[]>([])
  const w = useWorkflow(), [selected, setSelected] = useState(''), [kind, setKind] = useState(mode==='participation-review'?'participation':'membership'), [reason, setReason] = useState(''), [confirmed, setConfirmed] = useState(false), [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState({ legalName: '', representativeName: '', registrationNo: '', phone: '', branchId: w.operatorId }), [posId, setPosId] = useState(''), [branch, setBranch] = useState({ id: '', name: '', contactName: '', active: true })

  const company = w.companies.find(c => c.id === selected), profile = w.d.companyProfiles.find(c => c.companyId === selected)
  if (mode === 'membership-review' || mode==='participation-review') {
    const applications = kind === 'membership' ? w.d.applications.filter(a => a.operatorId === w.operatorId).map(a => ({ id: a.id, name: a.name, status: a.status, date: a.appliedAt })) : w.d.participationApplications.filter(a => a.operatorId === w.operatorId && a.businessId === w.businessId).map(a => ({ id: a.id, name: w.companies.find(c => c.id === a.companyId)?.legalName || a.companyId, status: a.status, date: '2026-10-04' }))
    const a = w.d.applications.find(a => a.id === selected), participation = w.d.participationApplications.find(a => a.id === selected)
    return <><AdminList title={kind==='membership'?'회원가입 심사':'사업 참여 심사'} description="홈페이지 회원가입과 회원사 신청·점포별 사업참여를 별도 업무로 관리합니다." rows={applications} rowKey={a => a.id} searchText={a => a.name}  columns={[{ key: 'name', label: '신청자', render: a => <button className="text-button" onClick={() => { setSelected(a.id); setReason(''); setPartyStoreIds(w.d.participationApplications.find(v => v.id === a.id)?.storeIds || []) }}>{a.name}</button> }, { key: 'date', label: '신청일', render: a => a.date }, { key: 'state', label: '상태', render: a => <WorkflowStatus code={a.status} /> }]} />{w.feedback}{selected && <section className="panel admin-detail"><h2>신청 상세</h2>{kind === 'membership' && a ? <DetailList items={[{ label: '법적 상호 / 사업자번호', value: `${a.name} / ${a.registrationNo}` }, { label: '대표자 / 연락처', value: `${a.representative} / ${a.phone}` }, { label: '이메일 / 주소', value: `${a.email} / ${a.address}` }, { label: 'POS / 서류', value: `${a.posId || '미지정'} / ${displayText(a.document)}` }, { label: '생성 회원사', value: a.companyId || '승인 전' }, { label: '처리 사유', value: a.reason }]} /> : <DetailList items={[{ label: '참여점포', value: participation?.storeIds.map(w.storeName).join(', ') }, { label: '선택 사업', value: w.business?.name }, { label: '처리 사유', value: participation?.reason }]} />}{kind === "participation" && participation && <fieldset><legend>참여점포 선택</legend>{w.stores.filter(s => s.companyId === participation.companyId).map(s => <Check key={s.id} label={s.name} checked={partyStoreIds.includes(s.id)} onChange={yes => setPartyStoreIds(yes ? [...partyStoreIds, s.id] : partyStoreIds.filter(id => id !== s.id))} />)}</fieldset>}<Field label="심사 사유"><textarea value={reason} onChange={e => setReason(e.target.value)} /></Field><div className="admin-actions">{['approved', 'rejected'].map(status => <button key={status} className="button secondary" disabled={['approved', 'rejected'].includes(applications.find(v => v.id === selected)?.status || '')} onClick={() => w.save({ kind: kind === 'membership' ? 'membership' : 'participation', id: selected, status, reason, ids: kind === "participation" ? partyStoreIds : undefined })}>{status === 'approved' ? '승인' : '반려'}</button>)}</div></section>}</>
  }
  if (mode === 'operators') {
    const accounts = w.data.accounts.filter(a => w.companies.some(c => c.id === a.companyId))
    return <><AdminList title="관리자 계정 관리" description="대표·부·일반 관리자 현황과 운영상 상태 변경. 추가 가입 승인 주체는 대표 또는 위임 부관리자입니다." rows={accounts} rowKey={a => a.id} searchText={a => `${a.name} ${a.loginId}`} columns={[{ key: 'name', label: '이름 / ID', render: a => <button className="text-button" onClick={() => { setSelected(a.id); setConfirmed(false) }}>{a.name}<span className="cell-sub">{a.loginId}</span></button> }, { key: 'co', label: '회원사 / Role', render: a => <>{w.companies.find(c => c.id === a.companyId)?.legalName}<span className="cell-sub">{w.data.roles.find(r => r.id === a.roleId)?.name}</span></> }, { key: 'scope', label: '접근점포 / 승인 주체', render: a => <>{Array.isArray(a.storeAccess) ? a.storeAccess.map(w.storeName).join(', ') : '회원사 전체'}<span className="cell-sub">대표/위임 부관리자 · 협회 운영관리</span></> }, { key: 'status', label: '상태', render: a => statuses.account[a.status] }]} />{w.feedback}{selected && <section className="panel admin-detail"><Check label="대표 관리자 변경 영향 확인" checked={confirmed} onChange={setConfirmed} /><div className="admin-actions">{[['active', '승인/활성'], ['suspended', '정지'], ['inactive', '비활성']].map(([status, label]) => <button key={status} className="button secondary" onClick={() => w.save({ kind: 'account', id: selected, status, confirmed })}>{label}</button>)}</div></section>}</>
  }
  if (mode === 'branches') return <><AdminList title="지회 관리" description="동적 상위 조직으로 지회와 소속 회원사를 관리합니다. 회원사의 지회 변경은 회원사 상세에서 직접 처리합니다." rows={w.branches} rowKey={b => b.id} searchText={b => b.name} onCreate={() => { setBranch({ id: crypto.randomUUID(), name: '', contactName: '', active: true }); setEditing(true) }} columns={[{ key: 'name', label: '지회', render: b => <button className="text-button" onClick={() => { setSelected(b.id); setBranch({ id: b.id, name: b.name, contactName: b.contactName || '', active: b.active }) }}>{b.name}</button> }, { key: 'companies', label: '회원사 / 점포', render: b => { const ids = w.companies.filter(c => w.data.organizations.find(o => o.id === c.organizationId)?.parentId === b.id).map(c => c.id); return `${ids.length}개 / ${w.stores.filter(s => ids.includes(s.companyId)).length}개` } }, { key: 'status', label: '상태', render: b => <Active value={b.active} /> }]} />{w.feedback}{selected && <BranchDetail id={selected} onClose={()=>setSelected('')} onEdit={()=>setEditing(true)} />}{editing && <Editor title="지회 등록/수정" onClose={() => setEditing(false)} onSave={() => w.save({ kind: 'branch', value: branch })}><Field label="지회명"><input value={branch.name} onChange={e => setBranch({ ...branch, name: e.target.value })} /></Field><Field label="담당자"><input value={branch.contactName} onChange={e => setBranch({ ...branch, contactName: e.target.value })} /></Field><Check label="사용" checked={branch.active} onChange={active => setBranch({ ...branch, active })} /></Editor>}</>
  if (mode === 'fees') return <FeesPage />
  return <><CompanyList onSelect={setSelected} />{w.feedback}{company && <CompanyDetail id={company.id} onClose={()=>setSelected('')} onEdit={()=>{setDraft({legalName:company.legalName,representativeName:company.representativeName,registrationNo:profile?.registrationNo||'',phone:profile?.phone||'',branchId:w.data.organizations.find(o=>o.id===company.organizationId)?.parentId||w.operatorId});setConfirmed(false);setReason('');setEditing(true)}} onPosChange={id=>{setPosId(w.stores.find(s=>s.id===id)?.posId||'');setKind(id);setConfirmed(false);setReason('')}} />}{editing && company && <Editor title="공식정보 수정" onClose={() => setEditing(false)} onSave={() => w.save({ kind: 'company', id: company.id, value: draft, reason, confirmed })}>{(['legalName', 'representativeName', 'registrationNo', 'phone'] as const).map((key, i) => <Field key={key} label={['법적 사업자명', '대표자', '사업자번호', '연락처'][i]}><input value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })} /></Field>)}<Field label="소속지회"><select value={draft.branchId} onChange={e => setDraft({ ...draft, branchId: e.target.value })}><option value={w.operatorId}>직할</option>{w.branches.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><Field label="변경 사유"><textarea value={reason} onChange={e => setReason(e.target.value)} /></Field><Check label="공식 서류를 확인했습니다" checked={confirmed} onChange={setConfirmed} /></Editor>}{w.stores.some(s => s.id === kind) && <DetailDialog title="점포 POS 종류 변경" onClose={() => setKind('membership')}><p className="notice-box">접속정보는 초기화되고 시스템 관리자 HUB에서 재설정·재검증해야 합니다. 기존 이력은 보존합니다.</p><Field label="사용 POS"><select value={posId} onChange={e => setPosId(e.target.value)}><option value="">미지정</option>{w.data.hub.poses.filter(p => p.active).map(p => <option key={p.id} value={p.id}>{displayText(p.name)}</option>)}</select></Field><Field label="변경 사유"><textarea value={reason} onChange={e => setReason(e.target.value)} /></Field><Check label="연동 영향과 재검증을 확인했습니다" checked={confirmed} onChange={setConfirmed} /><button className="button primary" onClick={() => { if (!w.save({ kind: 'storePos', id: posId, storeId: kind, reason, confirmed })) setKind('membership') }}>POS 종류 저장</button></DetailDialog>}</>
}
