import { useState } from 'react'
import { useWorkflow } from '../../state/useWorkflow'
import { companyFeeSummary } from '../../data/associationSummary'
import { won } from '../../data/workflowFormat'
import { displayText } from '../../data/workflowPresentation'
import { statuses } from '../../types/status'
import DetailDrawer from '../../components/workflow/DetailDrawer'
import DataTable from '../../components/workflow/AssociationTable'
import { DetailList } from '../../components/common/ui'
import WorkflowStatus from '../../components/workflow/WorkflowStatus'
import { WorkflowKpis } from '../../components/workflow/WorkflowUI'

export function CompanyDetail({id,onClose,onEdit,onPosChange}:{id:string;onClose:()=>void;onEdit:()=>void;onPosChange:(id:string)=>void}) {
 const w=useWorkflow(), [tab,setTab]=useState('basic'),[storeId,setStoreId]=useState(''),c=w.companies.find(c=>c.id===id), profile=w.d.companyProfiles.find(p=>p.companyId===id), stores=w.stores.filter(s=>s.companyId===id), accounts=w.data.accounts.filter(a=>a.companyId===id),fees=companyFeeSummary(w.data,id)
 if(!c)return null
 const org=w.data.organizations.find(o=>o.id===c.organizationId),parts=w.data.participations.filter(p=>stores.some(s=>s.id===p.storeId)),dueIds=w.d.dues.filter(d=>d.companyId===id).map(d=>d.id),receipts=w.d.receipts.filter(r=>r.companyId===id),related=new Set([id,c.organizationId,...stores.map(s=>s.id),...stores.map(s=>s.organizationId),...accounts.map(a=>a.id),...receipts.map(r=>r.depositId),...w.d.applications.filter(a=>a.companyId===id).map(a=>a.id)])
 const changes=w.data.changes.filter(change=>{const after=change.after as {target?:string;id?:string};return related.has(after?.target||after?.id||'')})
 return <DetailDrawer title="회원사 상세" context={`${c.legalName} > 회원사 상세`} onClose={onClose}><div className="association-tabs" role="tablist" aria-label="회원사 상세 탭">{[['basic','기본정보'],['stores','점포'],['accounts','관리자'],['participation','사업참여'],['fees','회비/수납'],['history','변경이력']].map(([key,label])=><button role="tab" aria-selected={tab===key} key={key} onClick={()=>setTab(key)}>{label}</button>)}</div>
 {tab==='basic'&&<section className="panel admin-detail"><div className="panel-heading"><h3>{c.legalName}</h3><button className="button secondary" onClick={onEdit}>공식정보 수정</button></div><DetailList items={[{label:'사업자번호',value:profile?.registrationNo},{label:'대표자',value:c.representativeName},{label:'소속지회',value:w.data.organizations.find(o=>o.id===org?.parentId)?.name||'직할'},{label:'연락처 / 주소',value:`${profile?.phone||'미등록'} / ${profile?.address||'미등록'}`},{label:'사업자등록증',value:displayText(profile?.document||'미등록')},{label:'상태',value:org?.active?'활성':'휴면'},{label:'점포 / 관리자',value:`${stores.length}개 / ${accounts.length}명`}]} /></section>}
 {tab==='stores'&&<section className="panel"><DataTable caption="회원사 점포" rows={stores} rowKey={s=>s.id} columns={[{key:'name',label:'점포',render:s=><button className="text-button" onClick={()=>setStoreId(s.id)}>{s.name}</button>},{key:'region',label:'지역 / 주소',render:s=>`${s.region} / ${w.d.storeProfiles.find(p=>p.storeId===s.id)?.address||'미등록'}`},{key:'pos',label:'POS / 연동상태',render:s=><>{displayText(w.data.hub.poses.find(p=>p.id===s.posId)?.name||'미지정')}<span className="cell-sub">{statuses.posConnection[s.posConnectionStatus]}</span></>},{key:'count',label:'참여사업',render:s=>parts.filter(p=>p.storeId===s.id&&p.status==='active').length}]} /></section>}
 {tab==='accounts'&&<section className="panel"><DataTable caption="회원사 관리자" rows={accounts} rowKey={a=>a.id} columns={[{key:'name',label:'이름 / ID',render:a=>`${a.name} / ${a.loginId}`},{key:'role',label:'Role',render:a=>w.data.roles.find(r=>r.id===a.roleId)?.name},{key:'scope',label:'접근점포',render:a=>Array.isArray(a.storeAccess)?a.storeAccess.map(w.storeName).join(', '):'회원사 전체'},{key:'status',label:'상태',render:a=>statuses.account[a.status]}]} /></section>}
 {tab==='participation'&&<section className="panel"><DataTable caption="회원사 사업참여" rows={parts} rowKey={p=>`${p.businessId}-${p.storeId}`} columns={[{key:'business',label:'사업',render:p=>w.data.businesses.find(b=>b.id===p.businessId)?.name},{key:'store',label:'점포',render:p=>w.storeName(p.storeId)},{key:'status',label:'참여상태',render:p=>statuses.participation[p.status]}]} /></section>}
 {tab==='fees'&&<><WorkflowKpis items={[["당월 청구",won(fees.billed)],['수납',won(fees.paid)],['미납 / 연체',won(fees.unpaid+fees.arrears)],['회비 상태',fees.status]]} /><section className="panel"><DataTable caption="회원사 회비 수납" rows={w.d.dues.filter(d=>dueIds.includes(d.id))} rowKey={d=>d.id} columns={[{key:'month',label:'대상월',render:d=>d.month},{key:'amount',label:'청구 / 납부',render:d=>`${won(d.amount)} / ${won(receipts.filter(r=>r.dueId===d.id).reduce((s,r)=>s+r.amount,0))}`},{key:'source',label:'출처',render:d=>displayText(d.source)}]} /></section><section className="panel"><DataTable caption="회원사 수납 이력" rows={receipts} rowKey={r=>r.id} columns={[{key:'at',label:'입금일',render:r=>w.d.deposits.find(d=>d.id===r.depositId)?.at||'초기이관'},{key:'category',label:'항목 / 금액',render:r=>`${r.category} / ${won(r.amount)}`},{key:'memo',label:'메모',render:r=>displayText(r.memo)}]} /></section></>}
 {tab==='history'&&<section className="panel"><DataTable caption="회원사 변경이력" rows={[...changes].reverse()} rowKey={c=>c.id} columns={[{key:'at',label:'처리일시',render:c=>c.at},{key:'actor',label:'처리자',render:c=>w.data.accounts.find(a=>a.id===c.actorId)?.name},{key:'type',label:'업무',render:c=>c.entity==='workflow:company'?'공식정보 변경':c.entity==='workflow:storePos'?'POS 종류 변경':c.entity==='workflow:membership'?'가입 승인':c.entity==='workflow:deposit'?'수납 확인':'관리정보 변경'},{key:'note',label:'사유',render:c=>displayText((c.after as {reason?:string}).reason||'변경 기록')}]} /></section>}
 {storeId&&<StoreDetail id={storeId} onClose={()=>setStoreId('')} onPosChange={()=>onPosChange(storeId)} />}
 </DetailDrawer>
}
export function StoreDetail({id,onClose,onPosChange}:{id:string;onClose:()=>void;onPosChange:()=>void}) {
 const w=useWorkflow(),s=w.stores.find(s=>s.id===id),p=w.d.storeProfiles.find(p=>p.storeId===id)
 if(!s)return null
 return <DetailDrawer title="점포 상세" context={`${w.companies.find(c=>c.id===s.companyId)?.legalName} > ${s.name}`} onClose={onClose}><section className="panel admin-detail"><h3>기본 / 운영정보</h3><DetailList items={[{label:'점포명 / 지역',value:`${s.name} / ${s.region}`},{label:'주소 / 전화',value:`${p?.address||'미등록'} / ${p?.phone||'미등록'}`},{label:'영업시간 / 휴무',value:`${p?.hours||'미등록'} / ${p?.holiday||'미등록'}`},{label:'배송 / 전화주문·픽업',value:`${p?.delivery?'가능':'없음'} / ${p?.pickup?'가능':'없음'}`},{label:'POS',value:displayText(w.data.hub.poses.find(v=>v.id===s.posId)?.name||'미지정')},{label:'POS 연동상태',value:statuses.posConnection[s.posConnectionStatus]}]} /><button className="button secondary" onClick={onPosChange}>POS 종류 변경</button></section><section className="panel"><h3>참여사업</h3><DataTable caption="점포 참여사업" rows={w.data.participations.filter(p=>p.storeId===id)} rowKey={p=>p.businessId} columns={[{key:'business',label:'사업',render:p=>w.data.businesses.find(b=>b.id===p.businessId)?.name},{key:'status',label:'상태',render:p=>statuses.participation[p.status]}]} /></section><section className="panel"><h3>담당 관리자</h3><DataTable caption="점포 담당 관리자" rows={w.data.accounts.filter(a=>a.companyId===s.companyId&&(!Array.isArray(a.storeAccess)||a.storeAccess.includes(id)))} rowKey={a=>a.id} columns={[{key:'name',label:'담당자 / Role',render:a=>`${a.name} / ${w.data.roles.find(r=>r.id===a.roleId)?.name}`},{key:'contact',label:'연락처',render:a=>a.phone||p?.phone||'미등록'},{key:'status',label:'상태',render:a=>statuses.account[a.status]}]} /></section></DetailDrawer>
}
export function BranchDetail({id,onClose,onEdit}:{id:string;onClose:()=>void;onEdit:()=>void}) {
 const w=useWorkflow(),branch=w.branches.find(b=>b.id===id),companies=w.companies.filter(c=>w.data.organizations.find(o=>o.id===c.organizationId)?.parentId===id),stores=w.stores.filter(s=>companies.some(c=>c.id===s.companyId)),fees=companies.map(c=>companyFeeSummary(w.data,c.id)),allocations=w.d.allocations.filter(a=>stores.some(s=>s.id===a.storeId)&&w.rounds.some(r=>r.id===a.roundId))
 if(!branch)return null
 return <DetailDrawer title="지회 상세" context={`${branch.name} > 지회 상세`} onClose={onClose}><section className="panel admin-detail"><div className="panel-heading"><h3>기본정보</h3><button className="button secondary" onClick={onEdit}>지회 수정</button></div><DetailList items={[{label:'지회명 / 코드',value:`${branch.name} / ${branch.code||'미등록'}`},{label:'담당자 / 연락처',value:`${branch.contactName||'미등록'} / ${branch.phone||'미등록'}`},{label:'사용상태',value:branch.active?'활성':'비활성'}]} /></section><WorkflowKpis items={[["회원사 / 점포",`${companies.length} / ${stores.length}`],['농할 참여 점포',stores.filter(s=>w.data.participations.some(p=>p.storeId===s.id&&p.businessId==='nonghal-2026'&&p.status==='active')).length],['선택사업 누적 배정',won(allocations.reduce((s,a)=>s+a.amount,0))],['당월 회비 수납',won(fees.reduce((s,f)=>s+f.paid,0))]]} /><section className="panel"><h3>회원사 / 점포 현황</h3><DataTable caption="지회 회원사" rows={companies} rowKey={c=>c.id} columns={[{key:'name',label:'회원사',render:c=>c.legalName},{key:'stores',label:'점포',render:c=>stores.filter(s=>s.companyId===c.id).map(s=>s.name).join(', ')},{key:'fees',label:'회비 상태',render:c=><WorkflowStatus code={companyFeeSummary(w.data,c.id).status} />}]} /></section><section className="panel"><h3>선택사업 예산 현황</h3><DataTable caption="지회 주차 예산" rows={w.rounds} rowKey={r=>r.id} columns={[{key:'round',label:'행사기간',render:r=>`${r.startsOn} ~ ${r.endsOn}`},{key:'budget',label:'점포 배정 / 집행',render:r=>`${won(allocations.filter(a=>a.roundId===r.id).reduce((s,a)=>s+a.amount,0))} / ${won(stores.reduce((s,st)=>s+w.execution(r.id,st.id).amount,0))}`}]} /></section><section className="panel admin-detail"><h3>회비 현황</h3><DetailList items={[{label:'당월 청구 / 수납',value:`${won(fees.reduce((s,f)=>s+f.billed,0))} / ${won(fees.reduce((s,f)=>s+f.paid,0))}`},{label:'미납 / 연체',value:won(fees.reduce((s,f)=>s+f.unpaid+f.arrears,0))},{label:'지회 관리자',value:w.data.accounts.filter(a=>a.organizationId===id).map(a=>`${a.name} · ${statuses.account[a.status]}`).join(', ')||'미등록'}]} /></section></DetailDrawer>
}
