import { useState } from 'react'
import { Editor, Field, Check } from '../../components/admin/AdminUI'
import { useWorkflow } from '../../state/useWorkflow'
import type { WeeklyRound, RepresentativeProduct } from '../../types/workflow'
export default function PlanEditor({source,onClose}:{source:'AT 연계'|'협회 직접 등록';onClose:()=>void}) {
 const w=useWorkflow(), direct=source==='협회 직접 등록'
 const [plan,setPlan]=useState<WeeklyRound>(()=>{const last=[...w.rounds].sort((a,b)=>b.endsOn.localeCompare(a.endsOn))[0];const start=new Date(`${last?.endsOn||'2026-10-14'}T00:00:00Z`);start.setUTCDate(start.getUTCDate()+1);const end=new Date(start);end.setUTCDate(end.getUTCDate()+6);const deadline=new Date(start);deadline.setUTCDate(deadline.getUTCDate()-1);return {id:crypto.randomUUID(),operatorId:w.operatorId,businessId:w.businessId,name:direct?'':'신규 행사주차',startsOn:start.toISOString().slice(0,10),endsOn:end.toISOString().slice(0,10),status:'draft',official:{items:direct?[]:w.d.representatives.map(p=>p.id),discount:20,personalLimit:10000,conditions:direct?'':'지정품목 할인 행사',source},operating:{budget:10000000,reserveRate:5,mode:'direct',deadline:deadline.toISOString().slice(0,16)}}})
 const [added,setAdded]=useState<RepresentativeProduct[]>([]),[itemName,setItemName]=useState(''),[unit,setUnit]=useState(''),[itemError,setItemError]=useState(''),[reserveMode,setReserveMode]=useState('rate')
 const items=[...w.d.representatives,...added], setOfficial=(patch:Partial<WeeklyRound['official']>)=>setPlan({...plan,official:{...plan.official,...patch}}),setOperating=(patch:Partial<WeeklyRound['operating']>)=>setPlan({...plan,operating:{...plan.operating,...patch}})
 return <Editor title={direct?'주차 계획 직접 등록':'AT 계획 가져오기'} onClose={onClose} onSave={()=>{if(!plan.name.trim()||!plan.startsOn||!plan.endsOn||!plan.operating.deadline||!plan.official.conditions.trim())return '필수 계획정보와 운영조건을 입력해 주세요.';if(plan.startsOn>plan.endsOn)return '행사 시작일은 종료일보다 늦을 수 없습니다.';if(!plan.official.items.length)return '대표품목을 최소 1개 선택해 주세요.';const error=w.save({kind:'round',value:plan,representatives:added.filter(p=>plan.official.items.includes(p.id))});if(!error)w.select('round',plan.id);return error}}>
 <h3 className="full-width">공식 계획정보</h3><p className="full-width">입력 출처: {source}</p><Field label="계획명"><input required value={plan.name} onChange={e=>setPlan({...plan,name:e.target.value})} /></Field>{(['startsOn','endsOn'] as const).map((key,i)=><Field key={key} label={['행사 시작일','행사 종료일'][i]}><input required type="date" value={plan[key]} onChange={e=>setPlan({...plan,[key]:e.target.value})} /></Field>)}
 <fieldset className="full-width"><legend>대표품목 · 복수 선택</legend><div className="plan-item-options">{items.map(p=><Check key={p.id} label={`${p.name} · ${p.unit}`} checked={plan.official.items.includes(p.id)} disabled={!direct} onChange={yes=>setOfficial({items:yes?[...plan.official.items,p.id]:plan.official.items.filter(id=>id!==p.id)})} />)}</div>{direct&&<div className="plan-add-item"><Field label="추가 품목명"><input value={itemName} onChange={e=>setItemName(e.target.value)} /></Field><Field label="품목 규격"><input value={unit} onChange={e=>setUnit(e.target.value)} placeholder="예: 1kg" /></Field><button type="button" className="button secondary" onClick={()=>{if(!itemName.trim()||!unit.trim()){setItemError('품목명과 규격을 입력해 주세요.');return}if(items.some(p=>p.name.trim()===itemName.trim()&&p.unit.trim()===unit.trim())){setItemError('동일 품목과 규격이 이미 있습니다.');return}const p={id:crypto.randomUUID(),name:itemName.trim(),unit:unit.trim()};setAdded([...added,p]);setOfficial({items:[...plan.official.items,p.id]});setItemName('');setUnit('');setItemError('')}}>품목 추가</button></div>}{itemError&&<p role="alert">{itemError}</p>}</fieldset>
 <Field label="정부 할인율 (%)"><input required type="number" min="0" max="100" step="0.1" readOnly={!direct} value={plan.official.discount} onChange={e=>setOfficial({discount:Number(e.target.value)})} /></Field><Field label="개인 할인한도 (원)"><input required type="number" min="0" readOnly={!direct} value={plan.official.personalLimit} onChange={e=>setOfficial({personalLimit:Number(e.target.value)})} /></Field><Field label="운영조건 / 비고"><textarea required readOnly={!direct} value={plan.official.conditions} onChange={e=>setOfficial({conditions:e.target.value})} /></Field>
 <h3 className="full-width">협회 운영정보</h3><Field label="주차 예산"><input required type="number" min="1" value={plan.operating.budget} onChange={e=>setOperating({budget:Number(e.target.value)})} /></Field><Field label="예비비 입력"><select value={reserveMode} onChange={e=>setReserveMode(e.target.value)}><option value="rate">비율 (%)</option><option value="amount">금액 (원)</option></select></Field><Field label={reserveMode==='rate'?'예비비율':'예비비 금액'}><input required type="number" min="0" max={reserveMode==='rate'?100:plan.operating.budget} step="any" value={reserveMode==='rate'?plan.operating.reserveRate:Math.round(plan.operating.budget*plan.operating.reserveRate/100)} onChange={e=>setOperating({reserveRate:reserveMode==='rate'?Number(e.target.value):plan.operating.budget?Number(e.target.value)/plan.operating.budget*100:0})} /></Field><Field label="등록 마감"><input required type="datetime-local" value={plan.operating.deadline} onChange={e=>setOperating({deadline:e.target.value})} /></Field><Field label="배정방식"><select value={plan.operating.mode} onChange={e=>setOperating({mode:e.target.value as 'direct'|'branch'})}><option value="direct">협회 → 점포</option><option value="branch">협회 → 지회 → 점포</option></select></Field>
 </Editor>
}
