import DataTable from '../../components/workflow/AssociationTable'
import WorkflowStatus from '../../components/workflow/WorkflowStatus'
import { displayText } from '../../data/workflowPresentation'
import { won } from '../../data/workflowFormat'
import { useState } from 'react'
import { Active, Check, Editor, Field } from '../../components/admin/AdminUI'
import { DetailList, PageHeader } from '../../components/common/ui'
import { WorkflowKpis } from '../../components/workflow/WorkflowUI'
import { useWorkflow } from '../../state/useWorkflow'
import type { FlyerPublication } from '../../types/workflow'
const titles: Record<string, string> = { 'public-participation': '참여 관리', 'public-data': '공개 데이터 관리', flyers: '전단 게시 관리', 'public-history': '연동 현황·이력' }
export default function PublicPage({ mode }: { mode: string }) {
  const w = useWorkflow(), [storeId, setStoreId] = useState(w.stores[0]?.id || ''), [flyer, setFlyer] = useState<FlyerPublication | null>(null), [error, setError] = useState('')
  const products = w.d.publicProducts.filter(p => p.operatorId === w.operatorId && p.businessId === w.businessId), flyers = w.d.flyers.filter(f => f.operatorId === w.operatorId && f.businessId === w.businessId), integrations = w.d.integrations.filter(i => i.operatorId === w.operatorId && i.businessId === w.businessId)
  const newFlyer = () => setFlyer({ id: crypto.randomUUID(), operatorId: w.operatorId, businessId: w.businessId, storeId, name: '차주 행사 전단', sourceName: '내장 SVG 전단 예시', status: 'uploaded', startsOn: '2026-10-08', endsOn: '2026-10-14', candidates: [] })
  return <><PageHeader title={titles[mode]} eyebrow="CONSUMER PLATFORM" description="공개 가능한 농할·행사상품과 전단만 선별합니다. 전송 실패 시 마지막 성공 공개 상태를 보존합니다." actions={mode === 'flyers' && <button className="button primary" onClick={newFlyer}>전단 등록</button>} />{w.feedback}<WorkflowKpis items={[["참여점포", w.stores.filter(s => w.data.participations.some(p => p.businessId === w.businessId && p.storeId === s.id && p.status === 'active')).length], ['공개 후보', products.length], ['공개 사용', products.filter(p => p.visible).length], ['연동 오류', integrations.filter(i => i.error).length]]} /><Field label="점포"><select value={storeId} onChange={e => setStoreId(e.target.value)}>{w.stores.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>
    {mode === 'public-participation' && <section className="panel"><DataTable caption="공개사업 참여" rows={w.stores} rowKey={s => s.id} columns={[{ key: 'store', label: '점포 / 지회 / 지역', render: s => `${s.name} / ${w.branchName(s.id)} / ${s.region}` }, { key: 'participation', label: '참여', render: s => <Active value={w.data.participations.some(p => p.businessId === w.businessId && p.storeId === s.id && p.status === 'active')} /> }, { key: 'source', label: '방식 / 공개 건수', render: s => `${s.posConnectionStatus === 'active' ? '연동형' : '게시형/파일형'} / ${products.filter(p => p.storeId === s.id && p.visible).length}` }, { key: 'action', label: '업무', render: s => <button className="text-button" onClick={() => w.save({ kind: 'publicParticipation', storeId: s.id, confirmed: true })}>참여 상태 변경</button> }]} /></section>}
    {mode === 'public-data' && <section className="panel"><DataTable caption="공개 데이터" rows={products.filter(p => p.storeId === storeId)} rowKey={p => p.id} columns={[{ key: 'name', label: '상품 / 유형', render: p => `${p.name} / ${p.source}` }, { key: 'price', label: '가격', render: p => won(p.price) }, { key: 'period', label: '행사기간', render: p => `${p.startsOn}~${p.endsOn}` }, { key: 'visible', label: '공개여부', render: p => <Active value={p.visible} /> }, { key: 'action', label: '설정', render: p => <button className="text-button" onClick={() => w.save({ kind: 'publicToggle', id: p.id })}>공개 On/Off</button> }]} /></section>}
    {mode === 'flyers' && <section className="panel"><DataTable caption="전단" rows={flyers} rowKey={f => f.id} columns={[{ key: 'name', label: '전단 / 원본', render: f => <button className="text-button" onClick={() => setFlyer(structuredClone(f))}>{f.name}<span className="cell-sub">{displayText(f.sourceName)}</span></button> }, { key: 'store', label: '점포 / 기간', render: f => `${w.storeName(f.storeId)} / ${f.startsOn}~${f.endsOn}` }, { key: 'status', label: '상태 / 후보', render: f => <><WorkflowStatus code={f.status} /><span className="cell-sub">{f.candidates.length}개 후보</span></> }, { key: 'action', label: '게시', render: f => <button className="text-button" disabled={f.status !== 'confirmed'} onClick={() => w.save({ kind: 'publishFlyer', id: f.id })}>게시 확정</button> }]} /></section>}
    {mode === 'public-history' && <section className="panel"><DataTable caption="공개 연동" rows={integrations} rowKey={i => i.storeId} columns={[{ key: 'store', label: '점포', render: i => <button className="text-button" onClick={() => setStoreId(i.storeId)}>{w.storeName(i.storeId)}</button> }, { key: 'success', label: '마지막 성공 / 다음 예정', render: i => `${i.lastSuccess || '없음'} / ${displayText(i.nextAt)}` }, { key: 'error', label: '오류 / 현재 공개', render: i => `${displayText(i.error || '정상')} / ${i.currentProductIds.length}건` }, { key: 'retry', label: '재처리', render: i => <div className="admin-actions"><button className="text-button" onClick={() => w.save({ kind: 'publicSend', storeId: i.storeId })}>재전송</button></div> }]} />{integrations.find(i => i.storeId === storeId)?.attempts.map((a, index) => <p key={index}>{a.at} / {displayText(a.result)} / {displayText(a.message)}</p>)}<DetailList items={[{ label: '현재 공개 (마지막 성공)', value: integrations.find(i => i.storeId === storeId)?.currentProductIds.map(id => products.find(p => p.id === id)?.name).join(', ') || '없음' }, { label: '다음 반영 예정', value: products.filter(p => p.storeId === storeId && p.visible).map(p => p.name).join(', ') || '없음' }]} /></section>}
    {flyer && <Editor title="전단 처리 / 후보 확인" onClose={() => setFlyer(null)} onSave={() => w.save({ kind: 'flyer', value: flyer })}><Field label="전단명"><input value={flyer.name} onChange={e => setFlyer({ ...flyer, name: e.target.value })} /></Field><Field label="점포"><select value={flyer.storeId} onChange={e => setFlyer({ ...flyer, storeId: e.target.value })}>{w.stores.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="게시 시작일"><input type="date" value={flyer.startsOn} onChange={e => setFlyer({ ...flyer, startsOn: e.target.value })} /></Field><Field label="게시 종료일"><input type="date" value={flyer.endsOn} onChange={e => setFlyer({ ...flyer, endsOn: e.target.value })} /></Field><div className="full-width"><svg viewBox="0 0 300 80" role="img" aria-label="내장 전단 예시"><rect width="300" height="80" fill="#e7f3ee" /><text x="20" y="45" fill="#137c69" fontSize="20">농할 행사 사과 / 계란 ()</text></svg><input aria-label="전단 이미지 파일" type="file" accept="image/*" onChange={e => { const f = e.target.files?.[0]; if (f) setFlyer({ ...flyer, sourceName: f.name + ' · 파일명만 보존 ' }) }} /><button type="button" className="button secondary" disabled={flyer.status === 'published'} onClick={() => setFlyer({ ...flyer, status: 'processed', candidates: [{ name: '농할 사과 1kg', price: 8000, checked: false }, { name: '행사 계란 30구', price: 5000, checked: false }] })}>상품후보 추출</button></div>{flyer.candidates.map((c, i) => <div key={i}><Check label={`공개 후보 ${c.name}`} checked={c.checked} onChange={checked => setFlyer({ ...flyer, candidates: flyer.candidates.map((v, j) => j === i ? { ...v, checked } : v) })} /><input aria-label={`후보 ${i + 1} 상품명`} value={c.name} onChange={e => setFlyer({ ...flyer, candidates: flyer.candidates.map((v, j) => j === i ? { ...v, name: e.target.value } : v) })} /></div>)}<button type="button" className="button secondary" onClick={() => { if (!flyer.candidates.some(c => c.checked)) { setError('상품후보를 선택해 주세요.'); return } setFlyer({ ...flyer, status: 'confirmed' }); setError('') }}>후보 확인 완료</button>{error && <p role="alert">{error}</p>}</Editor>}
  </>
}
