import { useState } from 'react'
import type { ReactNode } from 'react'
import { useWorkflow } from '../../state/useWorkflow'
import DetailDrawer from '../../components/workflow/DetailDrawer'
import DataTable from '../../components/workflow/AssociationTable'
import { WorkflowKpis } from '../../components/workflow/WorkflowUI'
import { DetailList } from '../../components/common/ui'
import WorkflowStatus from '../../components/workflow/WorkflowStatus'
import { won } from '../../data/workflowFormat'
import { displayText } from '../../data/workflowPresentation'
export function ClaimDetail({storeId,onClose}:{storeId:string;onClose:()=>void}) {
 const w=useWorkflow(),[item,setItem]=useState(''),b=w.batch,cl=w.d.claims.find(c=>c.batchId===b?.id),store=w.stores.find(s=>s.id===storeId),profile=w.d.companyProfiles.find(p=>p.companyId===store?.companyId)
 if(!b||!store)return null
 const tx=w.d.transactions.filter(t=>b.roundIds.includes(t.roundId)&&t.storeId===storeId),products=w.d.products.filter(p=>tx.some(t=>t.productId===p.id)),representatives=w.d.representatives.filter(p=>products.some(v=>v.representativeId===p.id)),rows=cl?cl.rows.filter(r=>r.storeId===storeId):tx.filter(t=>t.valid).map(t=>({transactionId:t.id,productName:products.find(p=>p.id===t.productId)?.name,amount:t.support})),amount=rows.reduce((s,r)=>s+r.amount,0)
 return <DetailDrawer title="정산 청구 상세" context={`${store.name} > ${b.name}`} onClose={onClose}><WorkflowKpis items={[["배정액",won(w.d.allocations.filter(a=>b.roundIds.includes(a.roundId)&&a.storeId===storeId).reduce((s,a)=>s+a.amount,0))],['집행액',won(tx.reduce((s,t)=>s+t.support,0))],['청구금액',won(amount)],['거래수',tx.length]]}/><section className="panel admin-detail"><h3>{cl?'최초 청구 Snapshot · 수정 불가':'청구 전 검증'}</h3><DetailList items={[{label:'최초 청구 보존본 / 생성시각',value:cl?`${cl.id} / ${cl.at}`:'청구 확정 전'},{label:'청구상태',value:<WorkflowStatus code={b.status}/>},{label:'계좌정보',value:profile?.bankVerified?'정상 검증 · ***-***-1234':'미검증 · 지급 준비 불가'},{label:'검증 결과',value:`통과 ${tx.filter(t=>t.valid).length}건 / 제외 ${tx.filter(t=>!t.valid).length}건`},{label:'제출 이력',value:cl?.submissions.map(s=>`${s.method} · ${s.at}`).join(', ')||'미제출'}]}/></section><section className="panel"><h3>품목 → 거래</h3><DataTable caption="품목별 청구" rows={representatives} rowKey={p=>p.id} columns={[{key:'item',label:'대표품목',render:p=><button className="text-button" aria-pressed={item===p.id} onClick={()=>setItem(p.id)}>{p.name}</button>},{key:'count',label:'거래수',render:p=>tx.filter(t=>products.some(v=>v.id===t.productId&&v.representativeId===p.id)).length},{key:'amount',label:'최초청구 / 청구예정',render:p=>won(rows.filter(r=>tx.some(t=>t.id===r.transactionId&&products.some(v=>v.id===t.productId&&v.representativeId===p.id))).reduce((s,r)=>s+r.amount,0))}]} /></section><section className="panel"><div className="panel-heading"><h3>{item?`${representatives.find(p=>p.id===item)?.name} > 청구 거래`:'전체 청구 거래'}</h3><button className="text-button" onClick={()=>setItem('')}>전체 품목</button></div><DataTable caption="청구 거래" rows={tx.filter(t=>!item||products.some(p=>p.id===t.productId&&p.representativeId===item))} rowKey={t=>t.id} columns={[{key:'tx',label:'거래 / 상품',render:t=>`${t.id} / ${rows.find(r=>r.transactionId===t.id)?.productName||products.find(p=>p.id===t.productId)?.name}`},{key:'at',label:'거래시각 / 수량',render:t=>`${t.at} / ${t.quantity}`},{key:'amount',label:'청구 / 제외금액',render:t=>won(rows.find(r=>r.transactionId===t.id)?.amount??t.support)},{key:'valid',label:'검증 / 제외사유',render:t=>t.valid?'통과':displayText(t.exclusion)}]}/></section><section className="panel"><DataTable caption="제외 거래 및 사유" rows={tx.filter(t=>!t.valid)} rowKey={t=>t.id} columns={[{key:'tx',label:'거래',render:t=>t.id},{key:'amount',label:'제외 지원금',render:t=>won(t.support)},{key:'reason',label:'제외사유',render:t=>displayText(t.exclusion)}]}/></section></DetailDrawer>
}
export function FinalDetail({payoutId,onClose,children}:{payoutId:string;onClose:()=>void;children:ReactNode}) {
 const w=useWorkflow(),p=w.d.payouts.find(p=>p.id===payoutId),b=w.batch
 if(!p||!b)return null
 const store=w.stores.find(s=>s.id===p.storeId),profile=w.d.companyProfiles.find(c=>c.companyId===store?.companyId),claim=w.d.claims.find(c=>c.batchId===b.id),initial=claim?.rows.filter(r=>r.storeId===p.storeId).reduce((s,r)=>s+r.amount,0)||0,cases=w.d.rejections.filter(c=>c.batchId===b.id&&c.storeId===p.storeId),rejected=cases.filter(c=>['accepted','rejected'].includes(c.status)).reduce((s,c)=>s+c.amount,0),final=w.d.finals.find(f=>f.batchId===b.id),date=p.status==='paid'?p.history.filter(h=>h.includes(': paid')).at(-1)?.slice(0,19)||'완료일 원본 미등록':'미지급'
 return <DetailDrawer title="최종정산 · 지급 상세" context={`${w.storeName(p.storeId)} > ${b.name}`} onClose={onClose}><WorkflowKpis items={[["최초 청구",won(initial)],['최종 인정',won(p.amount)],['최종 불인정',won(rejected)],['반환액',won(final?rejected:0)]]}/><section className="panel admin-detail"><DetailList items={[{label:'인정률',value:`${initial?(p.amount/initial*100).toFixed(1):0}%`},{label:'지급 대상액',value:won(p.amount)},{label:'지급상태',value:<WorkflowStatus code={p.status}/>},{label:'지급일',value:date},{label:'지급계좌',value:profile?.bankVerified?'정상 검증 · ***-***-1234':'미검증'},{label:'최종정산 보존본',value:final?`${final.id} / ${final.at}`:'미확정'},{label:'최초 청구 보존본',value:claim?`${claim.id} / ${claim.at}`:'미확정'},{label:'지급번호',value:p.paymentKey}]}/></section>{children}<section className="panel"><DataTable caption="관련 불인정 / 재심사" rows={cases} rowKey={c=>c.id} columns={[{key:'tx',label:'거래 / 사유',render:c=>`${c.transactionId} / ${displayText(c.reason)}`},{key:'amount',label:'금액',render:c=>won(c.amount)},{key:'state',label:'상태',render:c=><WorkflowStatus code={c.status}/>}]} /></section><section className="panel"><h3>지급 처리이력</h3>{p.history.map((h,i)=><p key={i}>{displayText(h)}</p>)}</section></DetailDrawer>
}
export function RejectionSummary({storeId,onClose,onCase}:{storeId:string;onClose:()=>void;onCase:(id:string)=>void}) {
 const w=useWorkflow(),cases=w.d.rejections.filter(c=>c.batchId===w.batch?.id&&c.storeId===storeId)
 return <DetailDrawer title="불인정 Case List" context={`${w.storeName(storeId)} > ${w.batch?.name}`} onClose={onClose}><section className="panel"><DataTable caption="점포 불인정 Case List" rows={cases} rowKey={c=>c.id} columns={[{key:'case',label:'Case / 거래',render:c=><button className="text-button" onClick={()=>onCase(c.id)}>{c.id} / {c.transactionId}</button>},{key:'reason',label:'사유 / 금액',render:c=>`${displayText(c.reason)} / ${won(c.amount)}`},{key:'state',label:'재심사 상태',render:c=><WorkflowStatus code={c.status}/>}]} /></section></DetailDrawer>
}
