import type { CommonCode, ExternalIntegration } from './systemCatalog.ts'
export interface TemplateVersion { id: string; version: string; startsOn: string; endsOn: string; status: 'active' | 'stopped' | 'expired'; required: string[]; optional: string[]; parserRef: string; modifiedAt: string }
export interface ExcelTemplate { id: string; name: string; area: string; description: string; usage: string; versions: TemplateVersion[] }
export interface JobRun { id: string; at: string; result: 'success' | 'failure'; count: number; seconds: number; message: string; retryOf?: string }
export interface Job { id: string; name: string; area: string; frequency: string; status: 'healthy' | 'delayed' | 'failed' | 'stopped'; nextAt: string; runs: JobRun[] }
export interface NotificationSetting { id: string; active: boolean; roleIds: string[]; organizationIds: string[]; channels: string[]; timing: string; repeat: boolean; threshold: number | null }
export interface AuditEvent { id: string; at: string; actor: string; organizationId: string; role: string; businessId: string; menu: string; action: string; entity: string; summary: string; result: 'success' | 'failure'; before: unknown; after: unknown; reason: string; related: string }
export interface OperationsData { version: 1; codes:CommonCode[]; integrations:ExternalIntegration[]; templates: ExcelTemplate[]; jobs: Job[]; notifications: NotificationSetting[]; events: AuditEvent[] }
export type OperationsCommand = {kind:'code';value:CommonCode} | {kind:'externalRun';integrationId:string;runId:string;action:'재처리'|'재검증';confirmed:boolean;reason:string;fail:boolean} | { kind: 'template'; value: ExcelTemplate } | { kind: 'version'; templateId: string; value: TemplateVersion } | { kind: 'versionStatus'; templateId: string; versionId: string; status: 'active' | 'stopped' } | { kind: 'notification'; value: NotificationSetting } | { kind: 'retry'; jobId: string; runId: string; reason: string; confirmed: boolean; fail: boolean } | { kind: 'download'; entity: string; menu: string; related: string }
