import type { PlatformData } from '../types/platform.ts'
import type { WorkflowCommand, WeeklyRound, StoreEventProduct, SaleTransaction, Notice, FlyerPublication, AnomalyCase } from '../types/workflow.ts'
import type { ExecutionSummary } from '../types/workflow.ts'
import { emptyConnection } from '../data/hubSeed.ts'
import { actionsFor, accountEnabled, canAccessProgram } from '../access/policy.ts'
import { workflowPermission } from '../data/workflowPermissions.ts'
import { liveCapabilities } from './hubStore.ts'
const ensure: (ok: unknown, message: string) => asserts ok = (ok, message) => { if (!ok) throw Error(message) }
const id = () => crypto.randomUUID()
export function organizationScope(p: PlatformData, root: string) { const ids = new Set([root]); let count = 0; while (count !== ids.size) { count = ids.size; p.organizations.filter(o => o.parentId && ids.has(o.parentId)).forEach(o => ids.add(o.id)) } return ids }
export function execution(p: PlatformData, roundId: string, storeId?: string) { const rows = p.workflow.transactions.filter(t => t.roundId === roundId && (!storeId || t.storeId === storeId)); return { amount: rows.reduce((s, t) => s + t.support, 0), count: rows.length } }
export function reserve(p: PlatformData, roundId: string) { const r = p.workflow.rounds.find(r => r.id === roundId); return (r?.operating.budget || 0) - p.workflow.allocations.filter(a => a.roundId === roundId).reduce((s, a) => s + a.amount, 0) }
export function executionSummary(p: PlatformData, roundId: string, storeId: string): ExecutionSummary { const total = execution(p, roundId, storeId), allocated = p.workflow.allocations.find(a => a.roundId === roundId && a.storeId === storeId)?.amount || 0, rate = allocated ? total.amount / allocated : 0; return { roundId, storeId, allocated, executed: total.amount, remaining: allocated - total.amount, rate, transactionCount: total.count, lastReceived: p.workflow.transactions.filter(t => t.roundId === roundId && t.storeId === storeId).at(-1)?.at || '', status: !total.amount ? 'no-sales' : rate >= 1 ? 'exhausted' : rate >= .8 ? 'near-limit' : 'running' } }
export function settlementTotals(p: PlatformData, batchId: string) { const claim = p.workflow.claims.find(c => c.batchId === batchId), cases = p.workflow.rejections.filter(c => c.batchId === batchId); const rejected = cases.filter(c => ['rejected', 'accepted'].includes(c.status)).reduce((s, c) => s + c.amount, 0), held = cases.filter(c => !['approved', 'rejected', 'accepted'].includes(c.status)).reduce((s, c) => s + c.amount, 0); return { initial: claim?.total || 0, rejected, held, accepted: (claim?.total || 0) - rejected - held } }
export function applyWorkflow(source: PlatformData, actorId: string, c: WorkflowCommand): PlatformData {
  const p = structuredClone(source), d = p.workflow, actor = p.accounts.find(a => a.id === actorId), role = p.roles.find(r => r.id === actor?.roleId)
  ensure(actor && actor.status === 'active' && role?.family === 'association' && actor.organizationId === c.operatorId, '소속 운영기관 관리자만 업무를 처리할 수 있습니다.')
  const [programId, defaultAction] = workflowPermission(c), program = p.programs.find(p => p.id === programId)
  const action = c.kind === 'branch' && !p.organizations.some(o => o.id === (c.value as { id: string }).id) || c.kind === 'product' && !d.products.some(o => o.id === (c.value as { id: string }).id) || c.kind === 'notice' && !d.notices.some(o => o.id === (c.value as { id: string }).id) ? 'create' : defaultAction
  ensure(accountEnabled(actor, p) && program && canAccessProgram(actor, c.businessId, program, p) && actionsFor(actor, programId, p).includes(action), '현재 Role·사업·프로그램에서 이 Action 권한이 없습니다.')
  const scope = organizationScope(p, c.operatorId), stores = p.stores.filter(s => scope.has(s.organizationId)), companies = p.companies.filter(s => scope.has(s.organizationId))
  const inStore = (storeId: string) => ensure(stores.some(s => s.id === storeId), '접근 범위 밖 점포입니다.')
  const posSupports = (storeId: string, capabilityId: string) => { const connection = p.hub.connections.find(v => v.storeId === storeId); return connection && liveCapabilities(p.hub, connection).some(v => v.id === capabilityId) }
  const publicParticipant = (storeId: string) => ensure(p.participations.some(v => v.storeId === storeId && v.businessId === c.businessId && v.status === 'active'), '활성 공개사업 참여점포만 공개할 수 있습니다.')
  const org = p.organizations.find(o => o.id === c.operatorId); ensure(org?.active, '중지된 조직입니다.')
  const business = p.businesses.find(b => b.id === c.businessId)
  ensure(business && p.businessOrganizations.some(m => m.businessId === business.id && m.organizationId === c.operatorId && m.role === 'operator'), '연결된 운영 사업을 확인해 주세요.')
  if (['round', 'confirmRound', 'allocate', 'budgetMove', 'product', 'confirmProduct', 'sale', 'claim', 'finalize', 'payout', 'publicToggle', 'publishFlyer', 'publicSend'].includes(c.kind)) ensure(business!.status === 'active', '진행 사업에서만 신규 업무를 처리할 수 있습니다.')
  const at = new Date().toISOString(), before = structuredClone(d), commonBefore = structuredClone({ organizations: p.organizations, companies: p.companies, stores: p.stores, accounts: p.accounts, participations: p.participations, connections: p.hub.connections })
  for (const co of companies) if (!d.companyProfiles.some(v => v.companyId === co.id)) d.companyProfiles.push({ companyId: co.id, registrationNo: '미등록', phone: '미등록', address: '미등록', document: '미등록', bankVerified: false })
  for (const st of stores) if (!d.storeProfiles.some(v => v.storeId === st.id)) d.storeProfiles.push({ storeId: st.id, phone: '미등록', address: '미등록', hours: '미등록', holiday: '미등록', delivery: false, pickup: false })
  if (!d.annualBudgets.some(v => v.businessId === c.businessId && v.operatorId === c.operatorId)) d.annualBudgets.push({ operatorId: c.operatorId, businessId: c.businessId, total: 0 })
  if (!d.settings.some(v => v.operatorId === c.operatorId)) d.settings.push({ operatorId: c.operatorId, deputyLimit: 0, brand: org.name })
  const round = () => { const r = d.rounds.find(r => r.id === c.id); ensure(r && r.operatorId === c.operatorId && r.businessId === c.businessId, '현재 사업의 주차를 확인해 주세요.'); return r! }
  const batch = () => { const b = d.batches.find(b => b.id === c.id); ensure(b && b.operatorId === c.operatorId && b.businessId === c.businessId, '현재 사업의 정산차수를 확인해 주세요.'); return b! }
  if (c.kind === 'membership') {
    const a = d.applications.find(a => a.id === c.id && a.operatorId === c.operatorId); ensure(a && !['approved', 'rejected'].includes(a.status), '미처리 가입 신청만 심사할 수 있습니다.')
    ensure(c.status === 'approved' || c.status === 'rejected' || c.status === 'reviewing', '심사 상태를 확인해 주세요.'); if (c.status === 'rejected') ensure(c.reason?.trim(), '반려 사유가 필요합니다.')
    a!.status = c.status as typeof a.status; a!.reason = c.reason || ''
    if (c.status === 'approved') {
      const companyId = id(), storeId = id(), companyOrg = id(), storeOrg = id(), parentId = c.ids?.[0] || c.operatorId
      ensure(scope.has(parentId), '소속 지회를 확인해 주세요.')
      p.organizations.push({ id: companyOrg, parentId, name: a!.name, code: `ORG-${companyId.slice(0, 8)}`, type: '회원사', active: true }, { id: storeOrg, parentId: companyOrg, name: `${a!.name} 기본점포`, code: `ORG-${storeId.slice(0, 8)}`, type: '점포', active: true })
      p.companies.push({ id: companyId, organizationId: companyOrg, legalName: a!.name, representativeName: a!.representative }); p.stores.push({ id: storeId, organizationId: storeOrg, companyId, name: `${a!.name} 기본점포`, region: '경기', posId: a!.posId, posConnectionStatus: 'unset' })
      p.accounts.push({ id: id(), loginId: `owner.${companyId.slice(0, 8)}`, name: a!.representative, organizationId: companyOrg, roleId: 'martOwner', companyId, status: 'active', storeAccess: 'company' })
      p.hub.connections.push(emptyConnection(storeId, a!.posId)); d.companyProfiles.push({ companyId, registrationNo: a!.registrationNo, phone: a!.phone, address: a!.address, document: a!.document, bankVerified: false }); d.storeProfiles.push({ storeId, address: a!.address, phone: a!.phone, hours: '미등록', holiday: '미등록', delivery: false, pickup: false }); d.dues.push({ id: id(), operatorId: c.operatorId, companyId, month: '2026-10', amount: 100000, source: '가입 생성 Mock' }); a!.companyId = companyId
    }
  } else if (c.kind === 'participation') {
    const a = d.participationApplications.find(a => a.id === c.id && a.operatorId === c.operatorId && a.businessId === c.businessId); ensure(a && a.status === 'pending', '미처리 참여 신청을 확인해 주세요.'); ensure(['approved', 'rejected'].includes(c.status || ''), '심사 결과를 선택해 주세요.'); if (c.status === 'rejected') ensure(c.reason?.trim(), '반려 사유가 필요합니다.')
    if (c.ids) { ensure(c.ids.length && new Set(c.ids).size === c.ids.length && c.ids.every(id => stores.some(s => s.id === id && s.companyId === a!.companyId)), '신청 회원사의 참여점포를 선택해 주세요.'); a!.storeIds = c.ids } a!.status = c.status as 'approved' | 'rejected'; a!.reason = c.reason || ''; if (c.status === 'approved') { for (const storeId of a!.storeIds) { inStore(storeId); const store = stores.find(s => s.id === storeId)!; ensure(store.companyId === a!.companyId, '신청 회원사의 점포만 참여할 수 있습니다.'); const old = p.participations.find(v => v.businessId === c.businessId && v.storeId === storeId); if (old) old.status = 'active'; else p.participations.push({ businessId: c.businessId, storeId, status: 'active' }); for (const [organizationId, businessRole] of [[store.organizationId, 'store'], [companies.find(co => co.id === store.companyId)!.organizationId, 'participant']] as const) if (!p.businessOrganizations.some(m => m.businessId === c.businessId && m.organizationId === organizationId)) p.businessOrganizations.push({ businessId: c.businessId, organizationId, role: businessRole }) } }
  } else if (c.kind === 'company') {
    const company = companies.find(v => v.id === c.id); ensure(company && c.confirmed && c.reason?.trim(), '공식 서류 확인과 변경 사유가 필요합니다.'); const v = c.value as { legalName: string; representativeName: string; registrationNo: string; phone: string; branchId: string }; ensure(v.legalName.trim() && v.representativeName.trim() && scope.has(v.branchId), '사업자명·대표자·소속지회를 확인해 주세요.'); Object.assign(company!, { legalName: v.legalName, representativeName: v.representativeName }); const node = p.organizations.find(o => o.id === company!.organizationId)!; ensure(v.branchId === c.operatorId || p.organizations.find(o => o.id === v.branchId)?.type === '지회', '운영기관 또는 지회를 선택해 주세요.'); node.name = v.legalName; node.parentId = v.branchId; Object.assign(d.companyProfiles.find(v => v.companyId === c.id)!, { registrationNo: v.registrationNo, phone: v.phone })
  } else if (c.kind === 'storePos') {
    inStore(c.storeId!); ensure(c.confirmed && c.reason?.trim(), 'POS 변경 영향과 재검증을 확인하고 사유를 입력해 주세요.'); ensure(!c.id || p.hub.poses.some(v => v.id === c.id && v.active), '사용 가능한 POS를 확인해 주세요.'); const s = stores.find(s => s.id === c.storeId)!, old = p.hub.connections.find(v => v.storeId === s.id)!; s.posId = c.id || null; s.posConnectionStatus = 'unset'; p.hub.connections = p.hub.connections.map(v => v.storeId === s.id ? { ...emptyConnection(s.id, s.posId), revision: old.revision + 1 } : v); p.hub.runs.unshift({ id: id(), at, storeId: s.id, posId: s.posId, interfaceId: null, action: '협회 POS 종류 변경', result: 'info', message: '기존 이력 보존 · 접속정보 재설정/재검증 필요', count: 0, revision: old.revision + 1 })
  } else if (c.kind === 'account') {
    const a = p.accounts.find(v => v.id === c.id); ensure(a && scope.has(a.organizationId) && a.companyId, '소속 회원사 계정을 확인해 주세요.'); ensure(c.status && ['active', 'suspended', 'inactive'].includes(c.status), '상태를 확인해 주세요.'); ensure(a!.roleId !== 'martOwner' || c.confirmed, '대표 관리자 변경 영향 확인이 필요합니다.'); if (a.roleId === 'martDeputy' && c.status === 'active') ensure(p.accounts.filter(v => v.companyId === a.companyId && v.id !== a.id && v.roleId === 'martDeputy' && v.status === 'active').length < (d.settings.find(v => v.operatorId === c.operatorId)?.deputyLimit ?? 0), '설정된 부관리자 상한을 초과합니다.'); a!.status = c.status as typeof a.status
  } else if (c.kind === 'branch') {
    const v = c.value as { id: string; name: string; contactName: string; active: boolean }; ensure(v.name.trim(), '지회명을 입력해 주세요.'); const old = p.organizations.find(o => o.id === v.id); ensure(!old || (scope.has(old.id) && old.type === '지회'), '소속 지회를 확인해 주세요.'); if (old) Object.assign(old, v); else p.organizations.push({ ...v, parentId: c.operatorId, type: '지회', code: `BR-${v.id.slice(0, 8)}` })
  } else if (c.kind === 'deposit') {
    const dep = d.deposits.find(v => v.id === c.id && v.operatorId === c.operatorId), v = c.value as { companyId: string; category: string; dueId: string; memo: string }; ensure(dep && dep.status !== 'confirmed' && companies.some(co => co.id === v.companyId), '미확정 입금과 소속 회원사를 확인해 주세요.'); const due = d.dues.find(vd => vd.id === v.dueId && vd.companyId === v.companyId); if (v.category === '회비') { ensure(due, '회비 청구월을 선택해 주세요.'); const paid = d.receipts.filter(r => r.dueId === due!.id).reduce((s, r) => s + r.amount, 0); ensure(paid + dep!.amount <= due!.amount, '회비 청구액을 초과합니다. 초과입금은 기타 항목으로 분류해 주세요.') } dep!.status = 'confirmed'; dep!.category = v.category; d.receipts.push({ id: id(), depositId: dep!.id, dueId: v.category === '회비' ? v.dueId : '', companyId: v.companyId, amount: dep!.amount, category: v.category, memo: v.memo }); d.aliases.push({ operatorId: c.operatorId, payer: dep!.payer, companyId: v.companyId })
  } else if (c.kind === 'annual') {
    ensure(Number.isSafeInteger(c.amount) && c.amount! > 0 && c.reason?.trim(), '양의 정수 예산과 사유가 필요합니다.'); const budget = d.annualBudgets.find(v => v.operatorId === c.operatorId && v.businessId === c.businessId)!; const committed = d.rounds.filter(r => r.operatorId === c.operatorId && r.businessId === c.businessId).reduce((s, r) => s + r.operating.budget, 0); ensure(c.amount! >= committed, '확정 주차 예산보다 연간 예산을 낮출 수 없습니다.'); budget.total = c.amount!
  } else if (c.kind === 'round') {
    const v = c.value as WeeklyRound; const added=c.representatives || []; ensure(added.every(p=>p.id && p.name.trim() && p.unit.trim()) && new Set(added.map(p=>p.id)).size===added.length && added.every(p=>!d.representatives.some(old=>old.id===p.id || old.name.trim()===p.name.trim() && old.unit.trim()===p.unit.trim())), '새 대표품목의 이름·규격·중복을 확인해 주세요.'); ensure(v.official.items.length>0 && new Set(v.official.items).size===v.official.items.length && v.official.items.every(id=>[...d.representatives,...added].some(p=>p.id===id)), '대표품목을 최소 1개 선택해 주세요.'); ensure(Number.isFinite(v.official.discount) && v.official.discount>=0 && v.official.discount<=100 && Number.isSafeInteger(v.official.personalLimit) && v.official.personalLimit>=0 && v.official.conditions.trim() && v.official.source.trim(), '공식 계획의 할인율·한도·운영조건·출처를 확인해 주세요.'); ensure(v.operating.mode==='direct'||v.operating.mode==='branch','예산 배정방식을 확인해 주세요.'); ensure(Number.isFinite(Date.parse(v.operating.deadline)), '상품 등록 마감일시를 확인해 주세요.'); ensure(v.operatorId === c.operatorId && v.businessId === c.businessId && v.name.trim(), '주차 Context와 계획명을 확인해 주세요.'); const start = new Date(v.startsOn + 'T00:00:00Z'), end = new Date(v.endsOn + 'T00:00:00Z'); ensure(start.getUTCDay() === 4 && end.getUTCDay() === 3 && end.getTime() - start.getTime() === 6 * 86400000, '행사주차는 목요일~수요일 7일입니다.'); ensure(!d.rounds.some(r => r.businessId === c.businessId && r.id !== v.id && r.startsOn <= v.endsOn && r.endsOn >= v.startsOn), '동일 사업의 행사기간이 중복됩니다.'); ensure(Number.isSafeInteger(v.operating.budget) && v.operating.budget > 0 && v.operating.reserveRate >= 0 && v.operating.reserveRate <= 100 && v.operating.deadline < v.startsOn, '예산·예비비·시작 전 마감을 확인해 주세요.'); ensure(d.rounds.filter(r => r.operatorId === c.operatorId && r.businessId === c.businessId && r.id !== v.id).reduce((s, r) => s + r.operating.budget, v.operating.budget) <= d.annualBudgets.find(a => a.operatorId === c.operatorId && a.businessId === c.businessId)!.total, '연간 예산을 초과합니다.'); ensure(!d.rounds.some(r => r.id === v.id), '기존 AT 원천 계획은 덮어쓰지 않습니다.'); d.representatives.push(...added.map(p=>({...p,name:p.name.trim(),unit:p.unit.trim()}))); d.rounds.push({ ...v, status: 'draft' })
  } else if (c.kind === 'confirmRound') {
    const r = round(); ensure(r.status === 'draft', '초안 주차만 확정할 수 있습니다.'); r.status = 'confirmed'; for (const store of stores.filter(s => p.participations.some(v => v.businessId === c.businessId && v.storeId === s.id && v.status === 'active'))) for (const item of r.official.items) d.products.push({ id: id(), roundId: r.id, storeId: store.id, representativeId: item, name: '', price: 0, photo: false, override: '', source: store.posConnectionStatus === 'active' ? 'POS' : 'Excel', status: 'draft', confirmedAt: '' })
  } else if (c.kind === 'endRound') { const r = round(); ensure(r.status === 'executing' && c.confirmed, '집행중 주차의 Mock 집행종료 확인이 필요합니다.'); r.status = 'ended'
  } else if (c.kind === 'allocate') {
    const r = round(); ensure(['confirmed', 'executing'].includes(r.status) && !d.transactions.some(t => t.roundId === r.id) && !d.claims.some(cl => cl.rows.some(t => t.roundId === r.id)), '집행/청구 전 주차에만 초기 배분할 수 있습니다.'); const participants = stores.filter(s => p.participations.some(v => v.businessId === c.businessId && v.storeId === s.id && v.status === 'active')); ensure(participants.length, '활성 참여점포가 없습니다.'); const weights = c.value as Record<string, number> | undefined; const sum = participants.reduce((s, st) => s + (weights?.[st.id] ?? 1), 0); ensure(sum > 0 && participants.every(st => Number.isFinite(weights?.[st.id] ?? 1) && (weights?.[st.id] ?? 1) > 0), '모든 참여점포의 양의 가중치를 입력해 주세요.'); const distributable = Math.floor(r.operating.budget * (1 - r.operating.reserveRate / 100)); let remaining = distributable; d.allocations = d.allocations.filter(a => a.roundId !== r.id); participants.forEach((st, i) => { const amount = i === participants.length - 1 ? remaining : Math.floor(distributable * (weights?.[st.id] ?? 1) / sum); remaining -= amount; d.allocations.push({ roundId: r.id, storeId: st.id, amount, branchId: r.operating.mode === 'branch' ? p.organizations.find(o => o.id === companies.find(co => co.id === st.companyId)!.organizationId)?.parentId || null : null }) }); d.ledger.push({ id: id(), operatorId: c.operatorId, businessId: c.businessId, roundId: r.id, storeId: '', at, type: c.method === 'Excel' ? '가중치 Excel 배분 Mock' : '균등배분', before: r.operating.budget, delta: -distributable, after: reserve(p, r.id), reason: c.reason || '주차 초기 배분', actor: actor!.name })
  } else if (c.kind === 'budgetMove') {
    const r = round(); inStore(c.storeId!); ensure(!d.claims.some(cl => cl.rows.some(t => t.roundId === r.id)), '청구 스냅샷에 포함된 주차는 배정을 변경할 수 없습니다.'); const a = d.allocations.find(a => a.roundId === r.id && a.storeId === c.storeId); ensure(a && Number.isSafeInteger(c.amount) && c.amount !== 0 && c.reason?.trim(), '배정 점포·정수 증감액·사유가 필요합니다.'); const old = reserve(p, r.id); ensure(c.amount! <= old && a!.amount + c.amount! >= execution(p, r.id, c.storeId).amount, '예비비 또는 미사용 잔액을 초과합니다.'); a!.amount += c.amount!; d.ledger.push({ id: id(), operatorId: c.operatorId, businessId: c.businessId, roundId: r.id, storeId: c.storeId!, at, type: c.amount! > 0 ? '추가배정' : '미사용 회수/예비비 전환', before: old, delta: -c.amount!, after: reserve(p, r.id), reason: c.reason!, actor: actor!.name })
  } else if (c.kind === 'product' || c.kind === 'confirmProduct') {
    const item = c.kind === 'product' ? c.value as StoreEventProduct : d.products.find(v => v.id === c.id)!; ensure(item, '행사상품을 선택해 주세요.'); inStore(item.storeId); if (c.kind === 'product' && item.source === 'POS') ensure(posSupports(item.storeId, 'product'), '점포에서 검증·활성화한 상품 Capability가 필요합니다. 파일/직접입력을 사용해 주세요.'); const r = d.rounds.find(r => r.id === item.roundId); ensure(r?.operatorId === c.operatorId && r.businessId === c.businessId && !d.claims.some(cl => cl.rows.some(t => t.roundId === r.id)), '현재 사업의 청구 전 상품만 수정할 수 있습니다.'); ensure(d.representatives.some(v => v.id === item.representativeId), '대표상품을 확인해 주세요.'); if (c.kind === 'confirmProduct' && item.override === 'not-running') { item.status = 'exception'; item.confirmedAt = at } else if (c.kind === 'confirmProduct') { ensure(item.name.trim() && item.price > 0 && item.photo, '상품명·판매가·대표상품 사진이 필요합니다.'); ensure(item.name.includes('농할') || item.override === 'name-change', '농할 문구 검증 또는 이름변경 예외가 필요합니다.'); item.status = item.override ? 'exception' : 'confirmed'; item.confirmedAt = at } else { ensure(!d.products.some(v => v.id === item.id && ['confirmed', 'exception'].includes(v.status)), '확정 상품은 새 판매상품으로 추가해 주세요.'); const old = d.products.find(v => v.id === item.id); if (old) Object.assign(old, { ...item, status: 'review' }); else d.products.push({ ...item, status: 'review' }) }
  } else if (c.kind === 'sale') {
    const t = c.value as SaleTransaction; inStore(t.storeId); if (t.source === 'POS') ensure(posSupports(t.storeId, 'sales'), '검증·활성화한 판매실적 Capability가 필요합니다.'); const r = d.rounds.find(r => r.id === t.roundId), product = d.products.find(v => v.id === t.productId && v.storeId === t.storeId && v.roundId === t.roundId); ensure(r?.operatorId === c.operatorId && r.businessId === c.businessId && ['confirmed', 'executing'].includes(r.status), '실행 가능한 주차를 확인해 주세요.'); ensure(product && product.override !== 'not-running' && ['confirmed', 'exception'].includes(product.status), '확정 행사상품만 집행할 수 있습니다.'); ensure(!d.claims.some(cl => cl.rows.some(row => row.roundId === t.roundId)), '청구 스냅샷 생성 후 거래를 변경할 수 없습니다.'); ensure(Number.isSafeInteger(t.quantity) && t.quantity > 0 && t.price > 0 && Number.isSafeInteger(t.support) && t.support >= 0 && t.support <= t.price * t.quantity, '수량·가격·지원금 정합성을 확인해 주세요.'); ensure(t.at.slice(0, 10) >= r.startsOn && t.at.slice(0, 10) <= r.endsOn, '행사기간 내 거래만 등록할 수 있습니다.'); const a = d.allocations.find(a => a.roundId === r.id && a.storeId === t.storeId); ensure(a && execution(p, r.id, t.storeId).amount + t.support <= a.amount, '배정예산을 초과합니다. 추가배정 후 입력해 주세요.'); d.transactions.push({ ...t, id: id(), valid: true, exclusion: '' }); r.status = 'executing'; const rate = execution(p, r.id, t.storeId).amount / a.amount; if (rate >= .8 && !d.anomalies.some(v => v.roundId === r.id && v.storeId === t.storeId && v.kind === '예산 소진 임박')) d.anomalies.push({ id: id(), roundId: r.id, storeId: t.storeId, kind: '예산 소진 임박', status: 'new', note: '공통 집행 집계 기준 80% Mock', source: 'cumulative' })
  } else if (c.kind === 'anomaly') { let a = d.anomalies.find(a => a.id === c.id); if (!a && c.value) { const candidate=c.value as AnomalyCase; const r=d.rounds.find(r=>r.id===candidate.roundId); ensure(r?.operatorId===c.operatorId&&r.businessId===c.businessId&&candidate.id===c.id&&candidate.id==='no-sales-'+r.id+'-'+candidate.storeId&&candidate.kind==='무실적'&&execution(p,r.id,candidate.storeId).amount===0,'현재 주차의 무실적 탐지건을 확인해 주세요.'); inStore(candidate.storeId); a={...candidate,status:'new',source:'cumulative',note:'해당 주차의 집행 자료에 거래 없음'}; d.anomalies.push(a) } ensure(a, '이상건을 선택해 주세요.'); ensure(d.rounds.some(r=>r.id===a!.roundId&&r.operatorId===c.operatorId&&r.businessId===c.businessId),'현재 사업의 이상건이 아닙니다.'); inStore(a!.storeId); ensure(['new', 'checking', 'resolved', 'watching'].includes(c.status || ''), '조치 상태를 확인해 주세요.'); a!.status = c.status as typeof a.status; a!.note = c.reason || ''
  } else if (c.kind === 'batch') { const rounds = d.rounds.filter(r => c.ids?.includes(r.id)); ensure(rounds.length && rounds.every(r => r.operatorId === c.operatorId && r.businessId === c.businessId && !d.batches.some(b => b.roundIds.includes(r.id))), '같은 사업의 미편입 주차를 선택해 주세요.'); d.batches.push({ id: id(), operatorId: c.operatorId, businessId: c.businessId, name: c.reason || '새 정산차수', roundIds: rounds.map(r => r.id), status: 'draft' })
  } else if (c.kind === 'claim') {
    const b = batch(); ensure(b.status === 'draft' && !d.claims.some(cl => cl.batchId === b.id), '최초 청구는 한 번만 확정합니다.'); const sourceRows = d.transactions.filter(t => b.roundIds.includes(t.roundId)); ensure(sourceRows.length && b.roundIds.every(r => d.rounds.find(v => v.id === r)?.status === 'ended'), '집행종료 주차의 거래가 필요합니다.'); const rows = sourceRows.filter(t => t.valid).map(t => ({ transactionId: t.id, storeId: t.storeId, roundId: t.roundId, productName: d.products.find(v => v.id === t.productId)?.name || '', quantity: t.quantity, amount: t.support })); d.claims.push({ id: id(), batchId: b.id, at, rows, total: rows.reduce((s, t) => s + t.amount, 0), excluded: sourceRows.filter(t => !t.valid).reduce((s, t) => s + t.support, 0), submissions: [] }); b.status = 'claimed'
  } else if (c.kind === 'submitClaim') { const b = batch(), cl = d.claims.find(cl => cl.batchId === b.id); ensure(cl && ['API', 'Excel'].includes(c.method || ''), '청구 스냅샷과 제출 방식을 선택해 주세요.'); cl!.submissions.push({ at, method: c.method as 'API' | 'Excel', reference: `mock-submit-${id()}` })
  } else if (c.kind === 'receiveRejections') { const b = batch(), cl = d.claims.find(cl => cl.batchId === b.id); ensure(cl && !d.rejections.some(v => v.batchId === b.id) && !d.finals.some(v => v.batchId === b.id), '청구 이후 AT 결과를 한 번 수신할 수 있습니다.'); const row = cl!.rows.find(r => r.amount >= 100000); ensure(row, '불인정 예시 금액 이상의 거래가 필요합니다.'); d.rejections.push({ id: id(), batchId: b.id, transactionId: row!.transactionId, storeId: row!.storeId, amount: 100000, reason: '상품명 기준 불충족 · AT 결과 Mock', status: 'mart-review', martOpinion: '', associationOpinion: '', evidence: [], history: [{ at, status: 'mart-review', note: 'AT 결과 원본 수신 Mock' }] }); b.status = 'reviewing'
  } else if (['appeal', 'reviewAppeal', 'receiveDecision'].includes(c.kind)) {
    const r = d.rejections.find(v => v.id === c.id); ensure(r, '불인정건을 선택해 주세요.'); inStore(r!.storeId); ensure(d.batches.some(b => b.id === r!.batchId && b.operatorId === c.operatorId && b.businessId === c.businessId), '현재 사업의 불인정건이 아닙니다.'); if (c.kind === 'appeal') { ensure(r!.status === 'mart-review' && c.reason?.trim(), '마트 검토 중인 건에 소명 의견이 필요합니다.'); r!.status = c.status === 'accepted' ? 'accepted' : 'appealed'; r!.martOpinion = c.reason!; r!.evidence = ['내장 Mock 거래명세서']; d.appeals.push({ id: id(), caseId: r!.id, opinion: c.reason!, evidence: '내장 Mock 거래명세서', at }) } else if (c.kind === 'reviewAppeal') { ensure(['appealed', 'association-review'].includes(r!.status) && c.reason?.trim(), '마트 소명과 협회 검토의견이 필요합니다.'); r!.status = 'at-review'; r!.associationOpinion = c.reason! } else { ensure(r!.status === 'at-review' && ['approved', 'rejected'].includes(c.status || ''), 'AT 재심사중인 결과만 모의 수신합니다.'); r!.status = c.status as 'approved' | 'rejected' } r!.history.push({ at, status: r!.status, note: c.reason || 'AT 최종 결과 Mock 수신' }); if (['accepted', 'rejected'].includes(r!.status)) { const tx = d.transactions.find(t => t.id === r!.transactionId)!, old = d.annualBudgets.find(a => a.operatorId === c.operatorId && a.businessId === c.businessId)!; const available = old.total - d.rounds.filter(v => v.operatorId === c.operatorId && v.businessId === c.businessId).reduce((s, v) => s + v.operating.budget, 0) + d.ledger.filter(v => v.operatorId === c.operatorId && v.businessId === c.businessId && v.type.startsWith("최종불인정")).reduce((s, v) => s + v.delta, 0); const existing = d.ledger.some(l => l.type === `최종불인정 환원:${r!.id}`); if (!existing) d.ledger.push({ id: id(), operatorId: c.operatorId, businessId: c.businessId, roundId: tx.roundId, storeId: tx.storeId, at, type: `최종불인정 환원:${r!.id}`, before: available, delta: r!.amount, after: available + r!.amount, reason: '재심사 종료 금액만 환원 · 연간 가용예산 집계', actor: actor!.name }); }
  } else if (c.kind === 'finalize') { const b = batch(), totals = settlementTotals(p, b.id); ensure(d.claims.some(cl => cl.batchId === b.id) && totals.held === 0 && !d.finals.some(f => f.batchId === b.id) && c.confirmed, '청구·재심사 종결·AT 최종정산 수신 확인이 필요합니다.'); d.finals.push({ id: id(), batchId: b.id, initial: totals.initial, accepted: totals.accepted, rejected: totals.rejected, refunded: totals.rejected, at }); b.status = 'final'; const claim = d.claims.find(cl => cl.batchId === b.id)!; for (const storeId of [...new Set(claim.rows.map(r => r.storeId))]) { const amount = claim.rows.filter(r => r.storeId === storeId).reduce((s, r) => s + r.amount, 0) - d.rejections.filter(r => r.batchId === b.id && r.storeId === storeId && ['accepted', 'rejected'].includes(r.status)).reduce((s, r) => s + r.amount, 0); if (amount > 0) d.payouts.push({ id: id(), batchId: b.id, storeId, amount, status: 'government-wait', paymentKey: `payment-${b.id}-${storeId}`, history: ['AT 최종정산 Mock 수신 · 정부지급 대기'] }) }
  } else if (c.kind === 'payout') { const b = batch(), rows = d.payouts.filter(v => v.batchId === b.id && (!c.storeId || v.storeId === c.storeId)); ensure(rows.length && c.confirmed, '지급대상과 처리 확인이 필요합니다.'); for (const row of rows) { inStore(row.storeId); if (c.status === 'received') { ensure(row.status === 'government-wait', '정부지급 대기 후 협회 입금을 확인합니다.'); row.status = 'received' } else if (c.status === 'ready') { ensure(row.status === 'received' && d.companyProfiles.find(co => co.companyId === stores.find(st => st.id === row.storeId)!.companyId)?.bankVerified, '협회 입금 및 정상 계좌 검증이 필요합니다.'); row.status = 'ready' } else if (c.status === 'processing') { ensure(['ready', 'failed'].includes(row.status) && c.reason?.trim(), '지급준비/실패 대상과 승인 사유가 필요합니다.'); row.status = 'processing' } else { ensure(row.status === 'processing' && ['paid', 'failed'].includes(c.status || ''), '지급중 대상의 은행 결과를 모의 반영합니다.'); row.status = c.status as 'paid' | 'failed' } row.history.push(`${at}: ${row.status} · ${c.reason || 'Mock 처리'}`) }
  } else if (c.kind === 'publicParticipation') { inStore(c.storeId!); ensure(c.confirmed, '참여 상태 변경을 확인해 주세요.'); const old = p.participations.find(v => v.businessId === c.businessId && v.storeId === c.storeId); if (old) old.status = old.status === 'active' ? 'stopped' : 'active'; else p.participations.push({ businessId: c.businessId, storeId: c.storeId!, status: 'active' }); if (!d.integrations.some(i => i.businessId === c.businessId && i.storeId === c.storeId)) d.integrations.push({ operatorId: c.operatorId, businessId: c.businessId, storeId: c.storeId!, lastSuccess: '', nextAt: 'Mock 대기', error: '', currentProductIds: [], attempts: [] })
  } else if (c.kind === 'publicToggle') { const item = d.publicProducts.find(v => v.id === c.id && v.operatorId === c.operatorId && v.businessId === c.businessId); ensure(item, '공개 상품을 선택해 주세요.'); inStore(item!.storeId); publicParticipant(item!.storeId); item!.visible = !item!.visible
  } else if (c.kind === 'flyer') { const v = c.value as FlyerPublication; inStore(v.storeId); ensure(v.operatorId === c.operatorId && v.businessId === c.businessId && v.startsOn <= v.endsOn, '게시 사업·기간을 확인해 주세요.'); const old = d.flyers.find(vv => vv.id === v.id); if (old) { ensure(old.status !== 'published', '게시된 원본은 새 전단으로 등록해 주세요.'); Object.assign(old, v) } else d.flyers.push(v)
  } else if (c.kind === 'publishFlyer') { const f = d.flyers.find(v => v.id === c.id && v.operatorId === c.operatorId && v.businessId === c.businessId); ensure(f && f.status === 'confirmed' && f.candidates.some(v => v.checked), '상품후보 확인 후 게시할 수 있습니다.'); publicParticipant(f!.storeId); f!.status = 'published'; f!.candidates.filter(v => v.checked).forEach(v => d.publicProducts.push({ id: id(), operatorId: c.operatorId, businessId: c.businessId, storeId: f!.storeId, productId: f!.id, name: v.name, price: v.price, startsOn: f!.startsOn, endsOn: f!.endsOn, visible: true, source: 'flyer' }))
  } else if (c.kind === 'publicSend') { inStore(c.storeId!); publicParticipant(c.storeId!); const integration = d.integrations.find(v => v.storeId === c.storeId && v.operatorId === c.operatorId && v.businessId === c.businessId); ensure(integration, '참여점포 연동을 확인해 주세요.'); const fail = c.status === 'failure'; integration!.error = fail ? 'Mock 전송 오류' : ''; if (!fail) { integration!.lastSuccess = at; integration!.currentProductIds = d.publicProducts.filter(v => v.businessId === c.businessId && v.storeId === c.storeId && v.visible && v.startsOn <= at.slice(0, 10) && v.endsOn >= at.slice(0, 10)).map(v => v.id) } integration!.attempts.push({ at, result: fail ? 'failure' : 'success', message: fail ? '현재 공개 스냅샷 보존' : '선별 공개 데이터 반영 Mock' })
  } else if (c.kind === 'notice') { const n = c.value as Notice; ensure(n.operatorId === c.operatorId && n.title.trim() && n.startsOn <= n.endsOn, '제목·조직·게시기간을 확인해 주세요.'); const old = d.notices.find(v => v.id === n.id); if (old) { ensure(old.operatorId === c.operatorId, '다른 조직의 게시물입니다.'); Object.assign(old, n) } else d.notices.push(n)
  } else if (c.kind === 'download') { ensure(c.id?.endsWith('.csv'), 'Mock CSV 파일을 확인해 주세요.')
  } else { const v = c.value as { deputyLimit: number; brand: string }; ensure(Number.isInteger(v.deputyLimit) && v.deputyLimit >= 0 && v.brand.trim(), '부관리자 상한과 표시명을 입력해 주세요.'); Object.assign(d.settings.find(v => v.operatorId === c.operatorId)!, v) }
  const changed = Object.keys(before).filter(key => JSON.stringify(before[key as keyof typeof before]) !== JSON.stringify(d[key as keyof typeof d]))
  const commonAfter = { organizations: p.organizations, companies: p.companies, stores: p.stores, accounts: p.accounts, participations: p.participations, connections: p.hub.connections }, commonKeys = Object.keys(commonBefore).filter(key => JSON.stringify(commonBefore[key as keyof typeof commonBefore]) !== JSON.stringify(commonAfter[key as keyof typeof commonAfter]))
  p.changes.push({ id: id(), at, actorId, entity: `workflow:${c.kind}`, before: { domain: Object.fromEntries(changed.map(key => [key, before[key as keyof typeof before]])), platform: Object.fromEntries(commonKeys.map(key => [key, commonBefore[key as keyof typeof commonBefore]])) }, after: { businessId: c.businessId, organizationId: c.operatorId, target: c.id || c.storeId, reason: c.reason || '', values: Object.fromEntries(changed.map(key => [key, structuredClone(d[key as keyof typeof d])])), platform: Object.fromEntries(commonKeys.map(key => [key, structuredClone(commonAfter[key as keyof typeof commonAfter])])) } })
  return p
}
