import { useAdmin } from '../../state/useAdmin'
import { businessRoleLabels } from '../../data/seed'
import { useState } from 'react'
import type { Business, BusinessOrganization } from '../../types/platform'
import { statuses } from '../../types/status'
import { newId } from '../../state/platformStore'
import { DataTable, DetailList, PageHeader } from '../../components/common/ui'
import { AdminList, Check, Editor, Field } from '../../components/admin/AdminUI'

export default function BusinessesPage({ mode = 'master' }: { mode?: 'master' | 'organizations' | 'programs' }) {
  const app = useAdmin(); const { data, business, save, feedback } = app
  const [selectedId, setSelectedId] = useState(data.businesses[0].id)
  const selected = mode === 'master' ? data.businesses.find(b => b.id === selectedId)! : business!
  const [draft, setDraft] = useState<Business | null>(null)
  const [tab, setTab] = useState<'detail' | 'organizations' | 'programs'>('detail')
  const activeTab = mode === 'master' ? tab : mode
  const [status, setStatus] = useState('all')
  return <>{feedback}{mode === 'master' ? <AdminList title="사업 마스터" description="사업은 기간·정책을 가진 운영 Context입니다. 조직과 별도의 마스터로 관리합니다." rows={data.businesses.filter(b => status === 'all' || b.status === status)} rowKey={b => b.id} searchText={b => `${b.name} ${b.code}`} onCreate={() => setDraft({ id: newId('business'), name: '', code: '', description: '', startsOn: '', endsOn: '', status: 'planned', applicationOpen: true, applicationRequired: true, approvalRequired: true, applicationUnit: '점포', participationPolicy: '', withdrawalPolicy: '' })} extraFilter={<Field label="사업 상태"><select value={status} onChange={e => setStatus(e.target.value)}><option value="all">전체</option>{Object.entries(statuses.business).map(([id, label]) => <option value={id} key={id}>{label}</option>)}</select></Field>} columns={[
      { key: 'name', label: '사업명', render: b => <button className="text-button" onClick={() => setSelectedId(b.id)}>{b.name}</button> }, { key: 'code', label: '사업코드', render: b => b.code }, { key: 'dates', label: '기간', render: b => `${b.startsOn} ~ ${b.endsOn}` }, { key: 'status', label: '상태', render: b => statuses.business[b.status] }, { key: 'org', label: '참여 조직', render: b => `${new Set(data.businessOrganizations.filter(m => m.businessId === b.id).map(m => m.organizationId)).size}개` },
    ]} /> : <PageHeader eyebrow="BUSINESS CONTEXT" title={mode === 'organizations' ? '참여 조직·역할' : '사업-프로그램 매핑'} description={`조회 사업: ${selected.name} · ${statuses.business[selected.status]}`} />}
    <section className="panel admin-detail admin-section"><div className="section-heading"><h2>{selected.name}</h2><button className="button secondary" onClick={() => setDraft({ ...selected })}>사업 수정</button></div>{mode === 'master' && <div className="admin-tabs">{(['detail', 'organizations', 'programs'] as const).map(t => <button key={t} className={tab === t ? 'selected' : ''} onClick={() => setTab(t)}>{t === 'detail' ? '기본 정보' : t === 'organizations' ? '참여 조직/역할' : '사용 프로그램'}</button>)}</div>}
      {activeTab === 'detail' && <DetailList items={[{ label: '사업 설명', value: selected.description || '미등록' }, { label: '상태', value: statuses.business[selected.status] }, { label: '참여 신청 필요', value: selected.applicationRequired !== false ? '필요' : '불필요' }, { label: '참여 신청', value: selected.applicationOpen ? '신청 가능' : '신청 닫힘' }, { label: '승인 필요', value: selected.approvalRequired ? '필요' : '불필요' }, { label: '신청 단위', value: selected.applicationUnit }, { label: '참여 정책', value: selected.participationPolicy || '미정' }, { label: '철회 정책', value: selected.withdrawalPolicy || '미정' }, ...(['supervisor', 'operator'] as const).map(r => ({ label: businessRoleLabels[r], value: data.businessOrganizations.filter(m => m.businessId === selected.id && m.role === r).map(m => data.organizations.find(o => o.id === m.organizationId)?.name).join(', ') || '미지정 (참여 조직/역할에서 지정)' })), { label: '사용 프로그램', value: data.businessPrograms.filter(m => m.businessId === selected.id).map(m => data.programs.find(p => p.id === m.programId)?.name).join(', ') || '미연결' }]} />}
      {activeTab === 'organizations' && <OrganizationMapping key={selected.id} selected={selected} />}{activeTab === 'programs' && <ProgramMapping key={selected.id} selected={selected} />}
      {['ended', 'archived', 'paused'].includes(selected.status) && <p className="notice-box">종료·보관·일시중지 사업은 신규 입력과 연결 변경을 제한합니다. 기존 연결과 변경 이력은 보존됩니다.</p>}
    </section>
    {draft && <Editor title={data.businesses.some(b => b.id === draft.id) ? '사업 수정' : '사업 등록'} onClose={() => setDraft(null)} onSave={() => { const result = save({ type: 'business', value: draft }); if (!result) setSelectedId(draft.id); return result }}>
      <Field label="사업명"><input required value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></Field><Field label="사업코드"><input required value={draft.code} onChange={e => setDraft({ ...draft, code: e.target.value })} /></Field><Field label="시작일"><input type="date" required value={draft.startsOn} onChange={e => setDraft({ ...draft, startsOn: e.target.value })} /></Field><Field label="종료일"><input type="date" required value={draft.endsOn} onChange={e => setDraft({ ...draft, endsOn: e.target.value })} /></Field>
      <Field label="사업 상태"><select value={draft.status} onChange={e => setDraft({ ...draft, status: e.target.value as Business['status'] })}>{Object.entries(statuses.business).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></Field><Field label="신청 단위"><input value={draft.applicationUnit ?? ''} onChange={e => setDraft({ ...draft, applicationUnit: e.target.value })} list="application-units" /><datalist id="application-units"><option>점포</option><option>회원사</option><option>조직</option></datalist></Field>
      <Field label="사업 설명"><textarea value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} /></Field><Field label="참여 정책"><textarea value={draft.participationPolicy ?? ''} onChange={e => setDraft({ ...draft, participationPolicy: e.target.value })} /></Field><Field label="철회 정책"><textarea value={draft.withdrawalPolicy ?? ''} onChange={e => setDraft({ ...draft, withdrawalPolicy: e.target.value })} /></Field><div><Check label="참여 신청 필요" checked={draft.applicationRequired !== false} onChange={applicationRequired => setDraft({ ...draft, applicationRequired })} /><Check label="참여 신청 가능" checked={draft.applicationOpen} onChange={applicationOpen => setDraft({ ...draft, applicationOpen })} /><Check label="승인 필요" checked={draft.approvalRequired ?? true} onChange={approvalRequired => setDraft({ ...draft, approvalRequired })} /></div><p className="muted full-width">관리감독기관·운영기관·참여조직 및 사용 프로그램은 저장 후 각각의 연결 탭에서 지정합니다. 종료·중지 시 신청은 자동으로 닫힙니다.</p>
    </Editor>}
  </>
}

function OrganizationMapping({ selected }: { selected: Business }) {
  const { data, save, feedback } = useAdmin()
  const [rows, setRows] = useState(data.businessOrganizations.filter(m => m.businessId === selected.id))
  const [orgId, setOrgId] = useState('')
  const [role, setRole] = useState<BusinessOrganization['role']>('participant')
  const [error, setError] = useState('')
  const locked = ['ended', 'archived', 'paused'].includes(selected.status)
  return <>{feedback}<p className="muted">조직은 여러 사업에 서로 다른 역할로 연결할 수 있습니다. 실행점포 연결은 참여 승인과 별도이며 신규 참여 상태는 초안입니다.</p><fieldset disabled={locked} className="mapping-fieldset"><div className="admin-actions"><Field label="연결할 조직"><select value={orgId} onChange={e => setOrgId(e.target.value)}><option value="">조직 선택</option>{data.organizations.filter(o => o.active).map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></Field><Field label="사업 내 역할"><select value={role} onChange={e => setRole(e.target.value as BusinessOrganization['role'])}>{Object.entries(businessRoleLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></Field><button className="button secondary" disabled={!orgId} onClick={() => { if (rows.some(r => r.organizationId === orgId && r.role === role)) setError('이미 연결된 조직·역할입니다.'); else { setRows([...rows, { businessId: selected.id, organizationId: orgId, role }]); setError('') } }}>연결 추가</button></div>
    <DataTable rows={rows} rowKey={r => `${r.organizationId}:${r.role}`} caption="사업 참여 조직 역할" columns={[{ key: 'org', label: '조직', render: r => data.organizations.find(o => o.id === r.organizationId)?.name }, { key: 'role', label: '사업 내 역할', render: r => businessRoleLabels[r.role] }, { key: 'action', label: '관리', render: r => <button className="text-button" aria-label={`${data.organizations.find(o => o.id === r.organizationId)?.name} ${businessRoleLabels[r.role]} 연결 해제`} onClick={() => setRows(rows.filter(row => row !== r))}>연결 해제</button> }]} /><button className="button primary" onClick={() => setError(save({ type: 'businessOrganizations', businessId: selected.id, values: rows }) ?? '')}>조직 연결 저장</button></fieldset>{error && <p role="alert" className="form-error">{error}</p>}<p className="muted">연결 해제는 조직·점포 및 참여 이력을 삭제하지 않습니다. 변경사항은 저장 후 반영됩니다.</p></>
}
function ProgramMapping({ selected }: { selected: Business }) {
  const { data, save, feedback } = useAdmin()
  const [ids, setIds] = useState(data.businessPrograms.filter(m => m.businessId === selected.id).map(m => m.programId))
  const [error, setError] = useState('')
  const locked = ['ended', 'archived', 'paused'].includes(selected.status)
  return <>{feedback}<p className="muted">사업 업무 프로그램만 연결합니다. 전역/조직 마스터는 사업 연결과 독립적으로 유지됩니다. 연결 후 Role 조회 권한이 있어야 메뉴가 표시됩니다.</p><fieldset disabled={locked} className="mapping-fieldset"><div className="program-checks">{data.programs.filter(p => p.scope === 'business').map(p => <Check key={p.id} label={`${p.group} / ${p.name}${!p.active ? ' (사용중지)' : ''}`} checked={ids.includes(p.id)} onChange={on => setIds(on ? [...ids, p.id] : ids.filter(id => id !== p.id))} />)}</div><button className="button primary" onClick={() => setError(save({ type: 'businessPrograms', businessId: selected.id, programIds: ids }) ?? '')}>프로그램 연결 저장</button></fieldset>{error && <p role="alert" className="form-error">{error}</p>}</>
}
